### ISSUE TITLE
File upload error with invalid extension

### ISSUE THREAD

**Issue by vwoohu** [Desertsnowman/Caldera-Forms#104]
Hi 
I"m getting the following error when I upload a file with an extension that's not part of Caldera Options for File Upload that I set (doc,docx, png etc).  Any idea?  When I upload a .docx file it works fine.

Warning: file_exists() expects parameter 1 to be string, array given in /home/bixal3/public_html/wp-content/plugins/caldera-forms/classes/core.php on line 293
{"url":"\/careers\/?cf_id=8","result":"Redirecting","data":{"cf_id":"8"},"html":"
Redirecting<\/div>","type":"complete","form_id":"CF553325c927257","form_name":"Contact Us","status":"complete"}

**Comment by Desertsnowman** [comment]
tis a bug! I'll sort it out thanks.

**Comment by Desertsnowman** [comment]
sorted in 1.1.9.8

**Comment by Desertsnowman** [comment]
which is coming later today ;)

**Comment by vwoohu** [comment]
Thanks for the quick turnaround!

V

On Thu, Apr 23, 2015 at 4:44 AM, David Cramer <notifications@github.com>
wrote:

> which is coming later today ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Desertsnowman/Caldera-Forms/issues/104#issuecomment-95492433>
> .
>



-- 
-- 
Peace,

Vincent (Guang) Hu
The DC Health Coach, HHC, AADP
Transformative Health and Nutrition Counseling Uniquely Designed for Busy
Professionals

Phone: 301-793-4264  Fax: 270-512-0102

Meditation, Kundalini Yoga and Holistic Nutrition
Certified Holistic Health Counselor, Kundalini Yoga Instructor
www.dchealthcoach.com

**Comment by vwoohu** [comment]
What was the problem?

Unrecognized file type? or it didn't get uploaded at all?

V

On Thu, Apr 23, 2015 at 11:38 AM, Vincent (Guang) Hu, CHHC, AADP <
vincenthu@gmail.com> wrote:

> Thanks for the quick turnaround!
>
> V
>
> On Thu, Apr 23, 2015 at 4:44 AM, David Cramer <notifications@github.com>
> wrote:
>
>> which is coming later today ;)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Desertsnowman/Caldera-Forms/issues/104#issuecomment-95492433>
>> .
>>
>
>
>
> --
> --
> Peace,
>
> Vincent (Guang) Hu
> The DC Health Coach, HHC, AADP
> Transformative Health and Nutrition Counseling Uniquely Designed for Busy
> Professionals
>
> Phone: 301-793-4264  Fax: 270-512-0102
>
> Meditation, Kundalini Yoga and Holistic Nutrition
> Certified Holistic Health Counselor, Kundalini Yoga Instructor
> www.dchealthcoach.com
>



-- 
-- 
Peace,

Vincent (Guang) Hu
The DC Health Coach, HHC, AADP
Transformative Health and Nutrition Counseling Uniquely Designed for Busy
Professionals

Phone: 301-793-4264  Fax: 270-512-0102

Meditation, Kundalini Yoga and Holistic Nutrition
Certified Holistic Health Counselor, Kundalini Yoga Instructor
www.dchealthcoach.com
