### ISSUE TITLE
How to add access to different User Roles

### ISSUE THREAD

**Issue by lmartins** [Desertsnowman/Caldera-Forms#105]
Hi,

I have a custom user-role for site administrators, with less permissions than the built-in Administrator. Is there a way I can give those users access to Caldera Forms management?

Have looked into the API docs but couldn't find anything about this.

Thank you

**Comment by Desertsnowman** [comment]
Hi there,
is this access rights for editing forms or viewing entries?

**Comment by lmartins** [comment]
Both if possible, although having the option to manage them independently would be really nice too.

**Comment by Desertsnowman** [comment]
ok, to view entries: edit the form, go to General Settings. then check "Pin to Menu" you can then select the role you want to access this menu. Under the Caldera Forms menu item, a user with the selected role will see the form name. clicking on it takes them to a view entries list.

for managing forms, I have not implemented this yet. I initially wanted to but decided against it for some reason. I'll see to adding it in a future update.

**Comment by lmartins** [comment]
Nice!! The "Pint to Menu" solves most cases for me.
Really digging your plugin man. Best forms editor in WordPress !

**Comment by Desertsnowman** [comment]
Thanks. I wouldn't say best, but it does have many uses.

**Comment by lmartins** [comment]
Well, that's probably right, but for my use case you can say it's the best usage experience I had so far. ;)

**Comment by Desertsnowman** [comment]
Glad to hear it!

**Comment by lmartins** [comment]
I've spoke to soon. To be able to implement this on my clients I do need to give them access. Is there any workaround apart from giving those users administrator access level?

**Comment by aburns348** [comment]
Is there any update on permissioning Caldera Forms?

**Comment by kennytheecat** [comment]
https://calderaforms.com/doc/caldera_forms_manage_cap/
