### ISSUE TITLE
Conditionals not working

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#106]
A user (Rocco) has reported to me that on update to 1.1.9.7 that conditionals stopped working. Reverting to 1.1.9.6 did resolved this issue. I am seeking additional details.

**Comment by Desertsnowman** [comment]
1.1.9.7 or .8 ?

**Comment by Desertsnowman** [comment]
conditions fixed in 1.2.0 should solve this. closing. open if not the case but I assume it is since there are no more reports of such.
