### ISSUE TITLE
Run action

### ISSUE THREAD

**Issue by kegita** [Desertsnowman/Caldera-Forms#109]
Hi! I have downloaded "Run Action"  addon but i doesn't work.I defined an action on "functions.php" and i have created a processor with this action.
Which is the problem? The code

add_action('testFunc', 'my_test_function');
function my_test_function( $data ){
    echo 'sdsd';
}"

**Comment by mdelmonte** [comment]
Hi, 

Did you ever resolve this issue? I am have the same exact problem and have not had any luck
