### ISSUE TITLE
Successful save notice is hidden by update form button.

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#110]
I like the successful save notice, but it renders behind the update form

**Comment by Shelob9** [comment]
Gif of bug: http://www.gfycat.com/LinedMasculineIndri

**Comment by sumobi** [comment]
Replicated this also 
![screen shot 2015-04-30 at 11 44 42 am](https://cloud.githubusercontent.com/assets/52581/7417802/5477f97c-ef2e-11e4-8d8b-24fde1b2f8eb.png)

**Comment by Shelob9** [comment]
@Desertsnowman On the site we're working on using dev branch the success message is in front of the button. Does that mean you fixed this already? It also seems right in Yellowstone.

**Comment by Desertsnowman** [comment]
I did make a fix in 1.2.x and also in yellowstone (along with the spinner visibility)
