### ISSUE TITLE
Slug created with underscore when exclamation mark is used

### ISSUE THREAD

**Issue by sumobi** [Desertsnowman/Caldera-Forms#117]
When creating a button and labelling it "Submit!" the slug was created with an underscore at the end. Would be nice to detect non standard characters and ignore things like the exclamation mark.

![screen shot 2015-04-30 at 11 51 34 am](https://cloud.githubusercontent.com/assets/52581/7417923/4718d7f0-ef2f-11e4-8291-73c273a9d27f.png)

**Comment by Desertsnowman** [comment]
+1
