### ISSUE TITLE
[Feature] Conditional Control Groups

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#128]
Let's say I'm making a form that has some checkboxes, each of which, when checked shows a bunch of additional fields. I can do that by setting every field to show if its checkbox is checked. But that's tedious and error prone.

But what if I was able to define a check box as a Conditional Control of the type "visibility" and then assign each of those fields to that group? Then they'd all hide show on that checkbox. Magic!

Even cooler, what if you could have a whole grid row/column hide and show based on a Conditional Control Group? Super double magic! Miracles I tell you, miracles from the gods on high!

**Comment by Desertsnowman** [comment]
I have been planning this for a long time. And now that I managed to get part of conduit in there it may happen even sooner.

**Comment by paaljoachim** [comment]
+++ 1..:)

**Comment by Shelob9** [comment]
This is now  a thing in CF 1.3 :cake:

**Comment by dlincoln** [comment]
It's very nice - would be totally awesome if you could test for null/empty fields. Or can you? Numeral 0 doesn't seem to work, nor an empty field, maybe I'm missing something?
