### ISSUE TITLE
Range Slider not working with Conditions

### ISSUE THREAD

**Issue by syedzeeshanali** [Desertsnowman/Caldera-Forms#139]
While making a form, I came across this Bug that if you want to show a Range Slider based upon a SELECT STATEMENT OPTION, one way or the other, the Range Sliders don't work. If you remove the Conditional statements they start working again. I think its a bug and can easily be sort out. Just wanted to inform you guys. 

Thanks for the great work & by the way Great Great Plugin Mates :100:

**Comment by Desertsnowman** [comment]
HI there,
I cant seem to replicate this. Can you try the current 1.2.x branch on here and see if it is still an issue?

**Comment by Desertsnowman** [comment]
Sorted.
