### ISSUE TITLE
Checkbox and Chrome

### ISSUE THREAD

**Issue by CAlexe** [Desertsnowman/Caldera-Forms#143]
Hello,

I have 2 problems with checkbox feature:

1. In Chrome the square for checking is not visible (in IE or Firefox is ok), please view : http://pic-oil.ro/en/hr/formular-inscriere/

2. The inline feature is not working. I put on the bottom of the form 1, 2 , 3 with inline checked and is showed in stacked .

Otherwise the plugin is great. Good job.

**Comment by Desertsnowman** [comment]
thanks, I'll take a look and see how to get it sorted.

**Comment by CAlexe** [comment]
the problems where resolved with the new update

tnx
