### ISSUE TITLE
Setting for View Entries not preserved upon Save

### ISSUE THREAD

**Issue by lmartins** [Desertsnowman/Caldera-Forms#144]
The setting which defines who can view form submissions in the Dashboard is broken since last update.
When you make any change to that field and save the form, it appears to have saved but if you come back to that page later, you'll see the inputs are all reset:

![screen shot 2015-05-07 at 17 02 40](https://cloud.githubusercontent.com/assets/151981/7519890/e5259fb8-f4da-11e4-87a6-a138c3c9e6ae.png)

**Comment by Desertsnowman** [comment]
thanks! sorted.

**Comment by lmartins** [comment]
I was about to bump this up, thanks for the feedback David.

**Comment by Desertsnowman** [comment]
you're welcome. Are you using this version or the one at wordpress.org?

**Comment by lmartins** [comment]
the one at wordpress.org
