### ISSUE TITLE
Should honey pot check really use isset()?

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#150]
Currently the honey pot check is run `if(isset($form['check_honey'])){` That means it is run if anything is set in that index. Pretty sure that means it always runs.

Wouldn't it make more sense if it was  `if(isset($form['check_honey']) && $form['check_honey'] ){` ? I might be missing something, hence why I'm not just changing it.

**Comment by Desertsnowman** [comment]
the setting is on a checkbox. since it uses baldricks form object, its it's unchecked the property doesnt exist. however I see your point from an array perspective where you would manually set it as false. So ye, I think making it ``` if( !empty($form['check_honey'])){ ``` would probably be better.
