### ISSUE TITLE
New french translation for 1.2.2 version

### ISSUE THREAD

**Issue by Jojaba** [Desertsnowman/Caldera-Forms#176]
Not an issue but a improvement...
Sorry, not familiar with git and github. I managed to upload the files I updated...
Here the files : https://github.com/Jojaba/caldera-forms

**Comment by Shelob9** [comment]
What you need to do is, in the Github interface, navigate to the files you want to change, and click edit. Make your changes there. That will create a pull request, that we can merge into this plugin, for you.

**Comment by Jojaba** [comment]
I opened a merge request using the windows github application. Not sure I did it to the right place (confusion between 1.2.x version and 1.2.2 version). Sorry if I did it the wrong way.

**Comment by Desertsnowman** [comment]
Thanks @Jojaba
