### ISSUE TITLE
Extra Commas In Output of HTML Fields From Toggle Switch Magic Tag

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#179]
Reported here: 

https://wordpress.org/support/topic/removing-commas-in-toggle-special-field-from-html-in-page-output?replies=2

Proposed fix is to remove comma, I think in the `join()` on L49 of field file https://github.com/Desertsnowman/Caldera-Forms/blob/1.2.x/fields/html/field.php#L49

**Comment by Desertsnowman** [comment]
that , is needed for checkboxes and/or multiple values. the problem is the toggle is a radio and not determining the checked state so its getting an empty string.
