### ISSUE TITLE
recaptcha js script is included in every page

### ISSUE THREAD

**Issue by mibuthu** [Desertsnowman/Caldera-Forms#189]
If the plugin is enabled the recaptcha javascript script will get included and downloaded in every page on the site if there is a form available or not.
This script shall only be included in pages where forms which uses recaptcha are included.

**Comment by Shelob9** [comment]
@Desertsnowman This is a good point. Loading recaptcha at wp_enqueue_scripts means we can't know whether or not its needed, so we just load it. We really should load some of the field specific scripts inside the form markup, so we can conditionally include/exclude.

**Comment by Desertsnowman** [comment]
I was sure I'm loading it via the field output. Strange.  I'll have to review it.

-------- Original message --------

**Comment by Shelob9** [comment]
Same thing is happening with select2.
