### ISSUE TITLE
Input Sanitization Destroys Accents

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#190]
Here is an example of text that should be allowed to pass as-is, but we mangle-sanatize:

`In Scuol können Sie – unter fachkundiger Anleitung oder auf eigene Faust – durch unser breitgefächertes Angebot stöbern.`

The good news is that `echo Caldera_Forms_Sanitize::sanitize( 'In Scuol können Sie – unter fachkundiger Anleitung oder auf eigene Faust – durch unser breitgefächertes Angebot stöbern.');` works just fine, so we just need to find where the over sanitization is happening, and replace with that.

**Comment by apsolut** [comment]
I get this problems even in Success Message.

with:
