### ISSUE TITLE
[caldera_form_modal] shortcode doesn't load scripts with do_shortcode()

### ISSUE THREAD

**Issue by JiveDig** [Desertsnowman/Caldera-Forms#195]
I only tested this on one local install, but it seems to be true. @Shelob9 told me about this awesome (undocumented?) feature. SUPER cool stuff, but would be much more powerful if it worked as a template tag with do_shortcode.

Or maybe there is a function/template tag instead of a the shortcode?

**Comment by JiveDig** [comment]
Okay, it looks like this line enqueues the modal files https://github.com/Desertsnowman/Caldera-Forms/blob/3fb346b9f1a7ea441297b6316a98bf280e910e2d/classes/core.php#L3586

Wondering if it would be better to register the modal script `wp_register_script` ahead of time, then just `wp_enqueue_script` it when the modal shortcode is used.

Will have to test.

**Comment by JiveDig** [comment]
Not trying to be annoying, just checking if this has any plan to get dealt with anytime soon. Have a need for it again coming up.

**Comment by Shelob9** [comment]
e605183 adds proper modals, #265 will add new shortcode syntax.
