### ISSUE TITLE
When field label is hidden, so is required astrick.

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#196]

**Comment by Desertsnowman** [comment]
and where to you propose I put the asterisk?

**Comment by Desertsnowman** [comment]
this is a usability issue not a bug. hiding labels is for making a form more compact. This has drawbacks like giving more feedback. not having a label means not having the required asterisk. You can always add `(required)` to the placeholder and also validation will still kick in when trying to submit.
