### ISSUE TITLE
Make reCAPTCHA field required

### ISSUE THREAD

**Issue by pablopaul** [Desertsnowman/Caldera-Forms#215]
Hey guys, 

how can I show that the reCAPTCHA field is required (which it is by default but the " * " is missing) ?

Thanks

**Comment by Desertsnowman** [comment]
erp... I have no idea! still trying to figure it out.

**Comment by pablopaul** [comment]
What exactly are you trying to figure out? ;-)

**Comment by Desertsnowman** [comment]
where to put "required" notices on fields that don't have labels. see #196

**Comment by pablopaul** [comment]
I use a label for the reCAPTCHA field but the * is missing since I cant check "required" in the backend:
![example](http://i.imgur.com/1zh0DAo.png)

**Comment by Desertsnowman** [comment]
:facepalm:
ok I'll check ans sort it out
