### ISSUE TITLE
Any plans on adding screen options or help?

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#216]
The user click the Forms sidebar link...

Sees the links New Form - Import and then Front-end style includes Alert, Form and Grid.

It is pretty clear what New form and Import does, but it is a mystery what Alert, Form and Grid does.

Tooltips will help.
Screen options and help can also help.

**Comment by Desertsnowman** [comment]
You may notice a branch 1.2.x-extended-settings 
Here I have been prototyping a more in depth config screen. I'm looking at cleaning up the admin page and make it a little more useful.

**Comment by paaljoachim** [comment]
Not sure where to look for it....Link?

**Comment by Desertsnowman** [comment]
It's a branch https://github.com/Desertsnowman/Caldera-Forms/tree/1.2.x-extended-settings

**Comment by paaljoachim** [comment]
Ok. Thanks.

**Comment by Desertsnowman** [comment]
It's just a prototype. It probably will change.  But it gives an idea that I'm rethinking the admin

**Comment by Shelob9** [comment]
closing as question answered
