### ISSUE TITLE
Field Validation When HTML5 Is Not A Thing

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#233]
Here it is reported Email Field Validation Not Working In iOS Safari:
https://wordpress.org/support/topic/email-field-validation-on-ios-not-work?replies=1

As far as I can tell from StackOverflow (http://stackoverflow.com/questions/7080166/html5-form-validation-not-working-with-iphone-android-or-safari) iOS Safari doesn't support HTML5 validation, because since when did Apple care about standards?

Since Safari, cursed be its name, is like 50% of mobile market share we probably need to address validation for non-HTML5 situations

**Comment by soumyabg** [comment]
+1

**Comment by Desertsnowman** [comment]
done
