### ISSUE TITLE
Buttons Need To Align with other inputs

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#242]
Not sure how widespread this is, but in 2015 a text input in same row with a button looks wonky
![screen shot 2015-09-01 at 8 03 29 pm](https://cloud.githubusercontent.com/assets/1994311/9620078/a01fc446-50e4-11e5-98e5-1da5a088f668.png)

**Comment by Desertsnowman** [comment]
Not really a bug, more a styling issue. hiding the label on the text field makes it work. however I added an "Add label space" option to aid in alignment.
