### ISSUE TITLE
Simple spam check  - 2+2 =4

### ISSUE THREAD

**Issue by fabtigger** [Desertsnowman/Caldera-Forms#252]
I love this form. So easy to use and logical.

I have a client who doesn't like the recaptcha spam check. They have foreign users who sometimes struggle with the spam pictures as they have a lot of western references which some of the users don't understand

Because of this they want to to add a simple spam check like
( 2+2 = [ ] )

Embarrassingly, I cant seem figure out how to create a field that requires the user to write an exact answer.

please help

Tigs x

**Comment by Desertsnowman** [comment]
Here you go, a simple field for you https://github.com/Desertsnowman/cf-simple-captcha
