### ISSUE TITLE
Admin entry viewer doesn't work for file-based forms

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#262]
I think this is because of the `$internal` arg of `Caldera_Forms::get_form()`. @Desertsnowman Is this doable?

**Comment by Desertsnowman** [comment]
It's supposed to be. This is a bug.

**Comment by Shelob9** [comment]
https://wordpress.org/support/topic/a-way-to-view-entries-in-interface-of-form-generated-with-php?replies=6

**Comment by Desertsnowman** [comment]
DOH! docs issue: need to add it to the admin filter as well. example:
```
add_filter( 'caldera_forms_get_forms', function( $forms ){
  // add form to admin under the ID my-include
  $forms['my-include'] = apply_filters( 'caldera_forms_get_form-my-include', array() );
  return $forms;
} );
```
