### ISSUE TITLE
Filter for orderby autopopulated terms/posts select field options

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#264]

**Comment by Desertsnowman** [comment]
I want to add an enhancement addon that will allow more features to this like filter by field and custom query etc..

**Comment by Shelob9** [comment]
This should not be an add-on. Making people install a 45th CF related plugin is not a substitute for what should be an option.

**Comment by Shelob9** [comment]
So I disagree with past-me. This shouldn't be a filter. If a user was like "sure I'll use a filter" then they could skip auto-populate and use "caldera_forms_render_get_field" but if they don't know how to use a filter, they need some sensible options? 
I made these UI options in e90db43 Not 100% sure UI is best and if this is too many options. So I put in branch and am re-assigning to @Desertsnowman to approve/fix/delete.

**Comment by dlincoln** [comment]
I am that user. The one who doesn't know how to use a filter (hey isn't that a son-type in the passover seder?). Definitely need a means of filtering in the UI, at least for taxonomies and probably for long post lists etc too.

**Comment by Desertsnowman** [comment]
merged with 1d6b30c
