### ISSUE TITLE
Add new modal shortcode arg, deprecated separate modal shortcode

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#265]
e6051835d2154feb6c1ba13977b1c0d98a1b6902 makes modals work right. Needs support in shortcode.

Syntax we discussed is `[caldera_forms id="cf12345" modal="true"]Click Me[/caldera_forms]` as preferred method. `[caldera_forms id="cf12345" modal="true"]` should also work, with form name as the link.

I suspect that `Caldera_Forms::render_form()` can no longer be used as the handler for the shortcode and we need a new handler method to accept the `$content`.

**Comment by Shelob9** [comment]
74afdb4 adds new handler and support for modal=true Actual JS needs work still.

**Comment by Desertsnowman** [comment]
This is done but needs more research its usable but want to have it beta run before making it a documented public feature and putting it in the shortcode inserter

**Comment by Shelob9** [comment]
I disagree. It's an in demand feature. We have the handler function. Tell me the HTML syntax and I'll make it work with modals.

**Comment by Desertsnowman** [comment]
Well go try it. It all works but I'm Unhappy with the styling and lack of options currently.

**Comment by Shelob9** [comment]
Modals do not work at all in my testing. Console error `Uncaught ReferenceError: webshim is not defined jquery.js?ver=1.11.3:5 Uncaught ReferenceError: webshim is not defined`

**Comment by Desertsnowman** [comment]
oh bother! sorry forgot to integrate the webshims for modals.

**Comment by Desertsnowman** [comment]
try now

**Comment by Shelob9** [comment]
I tried it. At first got errors for unset array keys, so ca46e0e

Feedback, testing in Chrome Mac:
1) Way too narrow -- hard set to 500px width. I say 75% on desktop, 95 or 100% on mobile.
2) If you resize a text input, it can escape the modal.
3) Placeholders that are magic tags are showing unrendered. In my test case I have `{user:user_email}` and its not rendering when logged in.

**Comment by Shelob9** [comment]
Works, but I am re-assigning to @Desertsnowman beacuse the default height is too tall. Should be dynamic. I make a form with two rows, and get a really tall model. See screenshot:

![screen shot 2016-04-08 at 5 45 00 pm](https://cloud.githubusercontent.com/assets/1994311/14398423/1313ace0-fdb2-11e5-839c-a639ae1b3124.png)
