### ISSUE TITLE
Form creation by editors ?

### ISSUE THREAD

**Issue by Jojaba** [Desertsnowman/Caldera-Forms#266]
I asked on support forum, no reply...
I would like to know if we can grnat the editors to create forms (for the moment only adin can do that).
Is there a way to add a cap like it is documented here : https://codex.wordpress.org/Function_Reference/add_cap ?

Thansk in advance.

**Comment by Shelob9** [comment]
This is something we are working on here: https://github.com/Desertsnowman/Caldera-Forms/issues/211 There is now a filter for what capability is required when ever we check capability. This will be completed in Caldera Forms 1.3.1

I am closing this as a duplicated since is is in progress via #211
