### ISSUE TITLE
HTML5 Validation Message Not Always Showing

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#275]
I have a 3 page form with required text fields on page 1 and 2 and a dropdown on page 3 that is hidden by default. Testing in Chrome, when I try and advanced to page 2, without filling out required text field on page 1, which is right, but I don't see the validation popup or see focus shifting to that field.

I removed hiding of pages 2 and 3 and made the conditionally hidden dropdown on page 3 show by triggering that conditional. Then the next page button showed the right validation error on page 1.

I declare 1.3.1 blocker

**Comment by Shelob9** [comment]
BTW Same issue in Safari for OSX (all my iOS devices are charging right now) which is actually a good sign, I made this test to check validation in Safari.

**Comment by Shelob9** [comment]
I forgot to mention, behavior is consistent between Safari OSX, iOS9 and iOS7.

**Comment by Desertsnowman** [comment]
Cool, will do more testing on multipage and get it right. Glad its consistent.

**Comment by Shelob9** [comment]
This is fixed
