### ISSUE TITLE
Confirm Password field name not correct when label hidden 

### ISSUE THREAD

**Issue by JonBarrett** [Desertsnowman/Caldera-Forms#276]
Firstly, great plugin! I've never used Github so let me know if I've put this message in the wrong place.

I have created a registration form with 'confirm password' on and 'hide labels' on. In the layout builder the field names are correct. See: http://screencast.com/t/ht7dyGdmF

However, when the form renders, the field names are duplicate: See: http://screencast.com/t/tr1MTlOiU

**Comment by Shelob9** [comment]
This is now fixed in cf-users 1.2.1
