### ISSUE TITLE
Validation Tooltip For Safari doesn't always have border

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#279]
On an iPad mini in Safair iOS9 the validation tooltip has no border. It does in Safari OSX and iPhone 4s with iOS7...

@Desertsnowman  I'm putting on 1.3.1 but if you punt it to 1.3.2 I'll be OK with that.

**Comment by Desertsnowman** [comment]
I'll check styling and take it from there.

**Comment by Shelob9** [comment]
Closing as no longer relevant
