### ISSUE TITLE
Autoresponder mailer does not set HTML content type header

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#283]

**Comment by Shelob9** [comment]
ecc5863 makes HTML by default. No UI option, but if there was one  (I can't figure out checkboxes) then we could defeat it by setting config option 'html' false.

**Comment by Shelob9** [comment]
@Desertsnowman Add a UI or just leave it as a always on?

**Comment by Desertsnowman** [comment]
this is fine for now.
