### ISSUE TITLE
Don't check for export GET var on all pages, only on ours

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#284]
Causing a conflict reported here:
https://wordpress.org/support/topic/caldera-forms-plugin-compatibility

**Comment by Shelob9** [comment]
Hey @Desertsnowman This should be good, and I tested all import/export/create still works. Should only affect those, the rest are AJAX. Can you please idiot check me?

**Comment by Desertsnowman** [comment]
@Shelob9 - works for me can you merge it in?

**Comment by Shelob9** [comment]
No merge needed. I committed directly, just wanted your check. Closing.
