### ISSUE TITLE
hr field?

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#295]
What about adding a hr field so one can add it in to create a border or line between fields without going into the stylesheet?

**Comment by Shelob9** [comment]
Why not use an HTML field with an `<hr />` tag in it. If you need to, target by field slug.

**Comment by paaljoachim** [comment]
What about adding some suggestions uses to the HTML field docs, adding hr etc to it?
Some fancy full ways to use the HTML field.
Have a great weekend!
Caldera Forms is a very good contact form!

**Comment by paaljoachim** [comment]
O and another thing...
Can you guys add the TinyMCE element so one can easily just add stuff through that as an option to having to use the HTML element?
