### ISSUE TITLE
Wrong Date Handling in Caldera_Forms_Admin::get_entries

### ISSUE THREAD

**Issue by obstschale** [Desertsnowman/Caldera-Forms#303]
Hey,

I informed you already via Twitter that the date handling is not working correctly. I narrowed down the error to the point where the date is falsified.

But first things first. What am I trying to do?

I use `Caldera_Forms_Admin::get_entries` in a plugin to get the entries to perform some action on it in a shortcode. I use a date field in my caldera form of type `date_picker` using a formulaire of `dd.mm.yyyy`.

The value is saved correctly in the database but when I use  `Caldera_Forms_Admin::get_entries` the return value in the `data` array is a float like 28.3 when the entered date is 28.03.2015.

If the formulaire is `yyyy-mm-dd` the returned value is of type `int` and is only the year.

I already said that I found the code which alters my date. In `Caldera_Forms_Admin:670`:

```php
// maybe json?
$is_json = json_decode( $row->value, ARRAY_A );
if( !empty( $is_json ) ){
  $row->value = $is_json;
}
```

I used a `var_dump` before and after this statement and found this:

```php
string 'Before json_decode' (length=18)
string '2015-10-02' (length=10)
string 'After json_decode' (length=17)
int 2015
```

I couldn't find out why you use `json_decode` after all. Maybe you should over think this :wink:

**Comment by Shelob9** [comment]
Good find @obstschale The `json_decode()` there is for certain field types which store multiple values as JSON. We need to check if it is a date before the json check.
