### ISSUE TITLE
Add Conditions Field needs a tooltip or directions

### ISSUE THREAD

**Issue by DevinWalker** [Desertsnowman/Caldera-Forms#313]
**Scenario** A new user decides to add conditions to their form and they click "Add Condition" - a blank field appears.

**Problem** I have not idea what to do with this blank field - write the condition? I had to watch this video to realize it's only giving a name of the condition and that a whole bunch of other fields pop up after.

**Solution** Either show the additional fields grayed out to the right and/or display a tooltip or message that the user needs to give this condition a name.

![11-3-2015 3-57-44 pm](https://cloud.githubusercontent.com/assets/1571635/10925552/073b755e-8244-11e5-8f9e-879c0469a94f.png)

**Comment by Shelob9** [comment]
I agree. Should have placeholder text "Name Of Group"

**Comment by Shelob9** [comment]
Also, maybe the tab should be labeled as "Conditional Groups" it's too long and would look bad, but it would be more right.
