### ISSUE TITLE
MailChimp API Key needs to be continually added per form

### ISSUE THREAD

**Issue by DevinWalker** [Desertsnowman/Caldera-Forms#317]
Sorry if this isn't the place to report Add-on issues. The problem I'm running into is that each form I hookup to MailChimp requires I reenter my API key. I've created 3 forms and each time I had to open up mailchimp again. Can a global API key be stored?

![11-3-2015 10-22-34 pm](https://cloud.githubusercontent.com/assets/1571635/10931128/aae79450-8279-11e5-8c0d-774d57e030a8.png)

**Comment by DevinWalker** [comment]
Also, once saved the key should turn to a password field or similar so the plain API key doesn't display.

**Comment by Shelob9** [comment]
I'm closing this as " @Desertsnowman has a API key manager plugin he really should roll into the core plugin but a) we're busy and b) we've been programmed to think that 27 add-on plugins is a better end-user experience than one modular plugin c) #329 "
