### ISSUE TITLE
Form description should bump to new line in shortcode generator

### ISSUE THREAD

**Issue by DevinWalker** [Desertsnowman/Caldera-Forms#320]
This UI looks awkward to me because I feel the description should be contained on it's own line. That way it flows a bit better with the others. CSS display:block on that bad boy?

![11-3-2015 11-08-55 pm](https://cloud.githubusercontent.com/assets/1571635/10931830/06acb7ec-8280-11e5-8ea5-07f1a5543636.png)

**Comment by DevinWalker** [comment]
All text should remain to the right of the radio and now go below

**Comment by Desertsnowman** [comment]
fixed via 0029a12
