### ISSUE TITLE
Cannot activate MailChimp Add-on License

### ISSUE THREAD

**Issue by DevinWalker** [Desertsnowman/Caldera-Forms#326]
I have the Caldera Forms MailChimp Add-on installed and activated:

![11-4-2015 2-08-11 pm](https://cloud.githubusercontent.com/assets/1571635/10953575/8ec85f8c-82fd-11e5-9be1-258e0c4fc7f4.png)

I also have the Caldera License Manager open (wish this wasn't a separate plugin but that's another topic). When I go to the license manager I don't see the option to activate this add-on:

![11-4-2015 2-07-26 pm](https://cloud.githubusercontent.com/assets/1571635/10953598/acbd3b70-82fd-11e5-9b70-621caa143e4b.png)

I do see it in my purchase history:

![11-4-2015 2-07-13 pm](https://cloud.githubusercontent.com/assets/1571635/10953603/b2765574-82fd-11e5-8208-96032e2483dd.png)

Any ideas why it's not displaying?

**Comment by Shelob9** [comment]
Pretty sure this is fixed in 1.3.2 already. But lets keep this open to be sure.

**Comment by paaljoachim** [comment]
Glad to hear that it is fixed in 1.3.2!

**Comment by paaljoachim** [comment]
Btw Devin. One can Add a Processor with MailChimp even though it is not showing under the activate license manager.

**Comment by DevinWalker** [comment]
Yeah I know

On Tuesday, November 10, 2015, Paal Joachim Romdahl <
notifications@github.com> wrote:

> Btw Devin. One can Add a Processor with MailChimp even though it is not
> showing under the activate license manager.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Desertsnowman/Caldera-Forms/issues/326#issuecomment-155443115>
> .
>


-- 

Devin Walker

Founder & Lead Developer

P:

858-449-6460 <8584496460>

W:

http://wordimpress.com

433 G Street #201
San Diego, CA 92101 <https://goo.gl/maps/BePgp>
<https://www.facebook.com/wordimpressive>  <https://twitter.com/wordimpress>
  <https://plus.google.com/u/0/b/117062083910623146392/+Wordimpress/about>
<http://wordimpress.com/>

**Comment by Shelob9** [comment]
Closing as got it sorted server-side
