### ISSUE TITLE
Inactive license warning dies and prevent entire page from saving

### ISSUE THREAD

**Issue by DevinWalker** [Desertsnowman/Caldera-Forms#327]
I just tried to embed a shortcode on a page with an inactive Caldera add-on license and was surprised when my screen went blank and I see:

![11-4-2015 1-57-46 pm](https://cloud.githubusercontent.com/assets/1571635/10953653/0641e880-82fe-11e5-83b1-f64152316af1.png)

I would suggest a better way to handle this so users don't lose their data and aren't alarmed when WordPress goes away.

**Comment by Desertsnowman** [comment]
thanks - will check it

**Comment by Desertsnowman** [comment]
issue was fixed I believe in the license manager. regardless, this is not coming from CF but the license manager.
