### ISSUE TITLE
Some users have issue with multi-page forms

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#339]
Some users are reporting issue not being able to advance to next page. I can not reproduce, but several report it...

**Comment by wpappdev** [comment]
Hi Josh,

Try reproducing it with a required field on an interior page. I experienced the same issue with the most recent version, it was validating the next page and would not let me advance. (Obviously no visuals though, as the validation messages where appearing on page 2). 

Also, I could not go back to a previous page without completing the required fields on the current page, which is undesirable, but may be a separate issue.

Justin

**Comment by Shelob9** [comment]
close via 19fab43
