### ISSUE TITLE
Change name of pinning forms.

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#342]
Hey

General Settings. (Or in the main forms screen as part of the quick edit bar)
What about pinning a form to the left sidebar? Instead of pinning Entries.
Then one could pin the most active forms having those more visible.

**Comment by Shelob9** [comment]
The name of that setting doesn't make any sense to me either.

I propose changing it to something like "Add entries as sub-menu item" but less wordy, while still explaining what it does. "Pinning" doesn't make sense.

**Comment by paaljoachim** [comment]
What about calling it "Active forms" IF pinning forms that is OR "Active Entries" IF pinning entries then a checkbox.

**Comment by Shelob9** [comment]
Close via 3435b5e
