### ISSUE TITLE
Next button in forms is not working.

### ISSUE THREAD

**Issue by SFPink** [Desertsnowman/Caldera-Forms#345]
As the title says the button to move to next form is not working. Tried looking into it however the javascript is minified so there's little I can do without reverting.

Edit:: 

I should have mentioned it was a multipart form. When I click next it seems to be validating the whole form and not moving on. 

Further testing shows that is because the radio checklist is required.

**Comment by Desertsnowman** [comment]
@SFPink can you check if the form has a required checkbox on another page other than the first?

**Comment by SFPink** [comment]
The first page has a required checkbox and the second has a required radio list. The checkbox on the first page was valid however.

I have implemented a temporary solution using a condition.

**Comment by Desertsnowman** [comment]
ok, radio on second page also counts. thanks. Pushing an update now that will fix it.

**Comment by Shelob9** [comment]
Fixed via 19fab43

**Comment by dccnow** [comment]
so this is still an isue - just got the same thing, and it seems to bebecause i have a required radio button on page 4 that my next buttons no longer work.
