### ISSUE TITLE
Import Entries?

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#348]
Hey

I want to switch out a bunch of the Contact Forms that I use with Caldera Forms, but I need a way to import CSV entries exported from other contact forms into Caldera.
How would I go about doing so today?

**Comment by Shelob9** [comment]
Entries are in a custom table. Export those rows in phpmyadmin on old site, import on new site. Make sure that form ID is the same and that entry IDs are unique.

**Comment by paaljoachim** [comment]
Thanks Josh!
If you guys could add an import button to Caldera Forms that would also be really useful for switching from another form to Caldera Forms. Very useful for a lot of people. I know I could take a lot of my existing forms export to CSV and then when it is in place import the CSV into Caldera Forms.

**Comment by Shelob9** [comment]
@paaljoachim This is a fairly big project you are suggesting -- in the immediate future, someone would have to be willing to pay to make it happen for us to focus on this specific need.

**Comment by paaljoachim** [comment]
I had no idea how large of project this would be. Thanks for the information.
