### ISSUE TITLE
Using Stripe addon without having a secure site?

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#350]
Hey

Is it possible to use the Stripe addon withouthaving a SSL certficate?
Meaning that somehow the Stipe addon can be used with other secure means then what is on the client site? Thanks.

**Comment by Shelob9** [comment]
No, it is not possible, nor should it be. You should have SSL when doing eCommerce. Not sure why you wouldn't want to.

**Comment by paaljoachim** [comment]
Ok. Thanks for the reply!
