### ISSUE TITLE
Display conflict in the top-level menus between Woothemes Sensei and Caldera Forms

### ISSUE THREAD

**Issue by christophherr** [Desertsnowman/Caldera-Forms#353]
Hi,

when using Woothemes Sensei and Caldera Forms, the Sensei CPT lesson gets removed from the top-level menus. 

The Sensei CPT lesson sets menu_position to 52.

Line 746 of classes/admin.php defines 
$this->screen_prefix[] = add_menu_page( __('Caldera Forms', 'caldera-forms'), __('Caldera Forms', 'caldera-forms'), Caldera_Forms::get_manage_cap(), $this->plugin_slug, array( $this, 'render_admin' ), 'dashicons-cf-logo', 52.999 );

Changing 52.999 to 54 would solve this conflict (and not create a new one with the Sensei CPT question).

I know this is like playing Battleship.

**Comment by Desertsnowman** [comment]
Whats the chance of asking Woothemes to change theirs?

**Comment by paaljoachim** [comment]
Well I just asked them....(sent an e-mail to their help line..:)

**Comment by Shelob9** [comment]
Close via 7cd861e

**Comment by christophherr** [comment]
@Shelob9 Sorry, I just realized that the quotes were and are missing around the priority with decimals.
Reference: https://codex.wordpress.org/Function_Reference/add_menu_page
`Risk of conflict can be reduced by using decimal instead of integer values, e.g. 63.3 instead of 63 (Note: Use quotes in code, IE '63.3').`

**Comment by Shelob9** [comment]
@christophherr I think the codex is wrong there. If you look in wp-admin/menu.php where the position value is used, you can see anything "integerish" would work so '63.3' or 63.3 is acceptable.

**Comment by christophherr** [comment]
@Shelob9 I can only say that using quotes solves the issue for me. 
I guess, because the data type is integer, only the whole number is being used and the decimal discarded. I did a quick test with Kint.
Without the quotes, only the whole number:
http://screencast.com/t/GLk18zQg
With quotes, the decimal:
http://screencast.com/t/rmryZPJJrv

**Comment by dwainm** [comment]
@Shelob9 thank you for the fix. We have a few menu items that we'd like to have close to each other. I'll make a note to tighten up the differnece in the menu order and move to a decimal system.
