### ISSUE TITLE
Uncaught Error: ReCAPTCHA has already been rendered in this element

### ISSUE THREAD

**Issue by webkingashu** [Desertsnowman/Caldera-Forms#354]
Don't know for some reason Recaptcha is not displaying on forms
When the page loads, the recaptcha loads and then hides

However the input field is created properly 

    <div class="col-sm-6  first_col">
    <script>
              jQuery( function($){
                      function init_recaptcha(){
                              var captch = $('#capfld_7040993_1');
                              captch.empty();
                              grecaptcha.render( captch[0], { "sitekey" : "mysitekey", "theme" : "light" } );
                      }
                      jQuery(document).on('click', '.reset_fld_7040993_1', function(e){
                              e.preventDefault();
                              init_recaptcha();
                      } );
                      setTimeout( function(){
                              init_recaptcha();
                      }, 1000);
              });
              </script><div class="form-group">
              <label for="fld_7040993_1" class="control-label">Captcha</label>
              <div class="">
              <input type="hidden" name="fld_7040993" value="fld_7040993_1" data-field="fld_7040993_1">
              <div id="capfld_7040993_1" class="g-recaptcha" data-theme="light" data-sitekey="mysitekey"></div>
              </div>
              </div>
              </div>
However there omes a js error in console

`Uncaught Error: ReCAPTCHA has already been rendered in this element`

Any help ?

**Comment by Desertsnowman** [comment]
I pushed an update  that fixes this - eaa74c6 - v1.3.1.2 is on wordpress.org as well.
