### ISSUE TITLE
Separate tab under plugins

### ISSUE THREAD

**Issue by Ribice** [Desertsnowman/Caldera-Forms#355]
Why does Caldera have its own separate tab under plugins?

![image](https://cloud.githubusercontent.com/assets/5403700/11246479/1c83d98a-8e18-11e5-84ea-973be5e66dc6.png)

**Comment by Desertsnowman** [comment]
there are 2 main reasons.
1: because I can.
2: because I have a lot of addons for Caldera Forms, and got tired of searching for them.

**Comment by paaljoachim** [comment]
Interesting!
A good idea.

**Comment by Desertsnowman** [comment]
this btw, was the inspiration for https://wordpress.org/plugins/plugin-groups/
