### ISSUE TITLE
Rementioning: Duplicate Field/ Row/ Group

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#358]
What happened with?

[Feature] Duplicate Field/ Row/ Group:
https://github.com/Desertsnowman/Caldera-Forms/issues/129

I am checking through some of the older issues. There are a few enhancement issues in there that would be nice to add.

**Comment by Shelob9** [comment]
@paaljoachim Please don't open duplicate issues. Keep the discussion in that issue.

**Comment by paaljoachim** [comment]
Ok gotcha.
