### ISSUE TITLE
Ajax submissions fail with ugly permalinks

### ISSUE THREAD

**Issue by Desertsnowman** [Desertsnowman/Caldera-Forms#361]
Been getting reports that ajax submissions are failing.
We need to figure this out before next release.

**Comment by Shelob9** [comment]
Me too. It's always when ugly permalinks are configured as `/cf-api/CFid` triggers a server 404, not a WordPress 404. BUT ugly permalinks work just fine for me testing in VVV (nginx server)

**Comment by Desertsnowman** [comment]
Need to sort this out. Will take a think this weekend while I try to get better.

**Comment by Desertsnowman** [comment]
Perhaps we should check for permalinks enabled else fallback to admin-ajax.

**Comment by Shelob9** [comment]
@Desertsnowman What if we switched to non-ajax submissions automatically if ajax 404ed?

**Comment by Desertsnowman** [comment]
Oh I like that a lot! So ajax returns 404, submit as normal

**Comment by Shelob9** [comment]
It's better to get the form entry in so data  isn't lost.

**Comment by Desertsnowman** [comment]
Revising this

**Comment by Shelob9** [comment]
#386 fixes should solve this, and now we have a fallback.
