### ISSUE TITLE
Inverted comma in label prevents saving of radio button

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#365]
User reports:
`Hi Josh, we’ve pickup on bug on radio buttons where a single inverted coma i.e. in the word ‘wouldn’t’ stops the data being saved to the database, when I changed it to ‘would not’ it worked OK.`

**Comment by kirbyhowarth** [comment]
The bug seems to be exclusive to the word 'wouldn't'?

**Comment by kirbyhowarth** [comment]
Nice one and thanks for your help.
