### ISSUE TITLE
Wrong checkbox values in email summary

### ISSUE THREAD

**Issue by Amentis1969** [Desertsnowman/Caldera-Forms#374]
I have these checkboxes in my form: Modul A, Modul B, Modul C. The data is being reported properly in the entry list. But in the email notfication for website admin and customers the values are wrong, it's showing this:

Modul C, Modul C, Modul C

I'm using magic tags for getting the checkbox values. If I use {summary} no checkbox values at all are submitted.

**Comment by Shelob9** [comment]
Related #299

**Comment by Shelob9** [comment]
Fixed via #487
