### ISSUE TITLE
Conditionals based on magic tags do not work

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#376]
Probably same root cause as #375

**Comment by Desertsnowman** [comment]
sorted it out here 5cc3f55

**Comment by Shelob9** [comment]
Reopening. I am trying to do a simple show a field if one field is greater than another. I use magic tag for one field in my comparison. It doesn't work.


![screen shot 2015-12-29 at 11 32 43 pm](https://cloud.githubusercontent.com/assets/1994311/12046298/93d33e22-ae84-11e5-8fb3-5582458b4702.png)

I also can't make greater than work with if I just use a number. Maybe greater than comparisons are broken?

**Comment by Desertsnowman** [comment]
oh wow. ye I never thought about that. Did that ever work?

**Comment by Desertsnowman** [comment]
I just checked and ye the tags show. Before the new conditionals tab, the fields where hidden to prevent this. 
It's about time though, I'll make it work.
