### ISSUE TITLE
PayPal processor breaks file upload attachments and links in e-mail

### ISSUE THREAD

**Issue by stefanmccall** [Desertsnowman/Caldera-Forms#380]
I've run into something that might be a bug with using the PayPal processor and attaching uploads to the mailer. Without the processor my upload is attached to the e-mail as well as the link showing up in the e-mail summary but as soon as I add the processor this stops working. I'm on the latest version of your software, as well as WordPress.

I set up a new form with just the uploader, a hidden value for price and a submit button just to test this out and got the same results as with my main form. Just to note, the uploads do go through, I can see them in the Uploads folder on the server but they are not being attached to the e-mail.

**Comment by Desertsnowman** [comment]
It seems strange since they are not related, but hey. Code is strange.
Thanks.

**Comment by Shelob9** [comment]
See #182 and #174 

I thought I fixed this via #282 Which was dealing with root issue that the file uploader didn't work with redirects.

**Comment by Desertsnowman** [comment]
@Shelob9 - no, that just converts a url to a file path, which is correct. The main reason here is the file upload handler. It looks for $_FILES to start the upload, but if it's missing then returns nothing. meaning the file is technically lost. I got a fix which I'll push in a sec.
