### ISSUE TITLE
Form shows javascript message after submitting and no longer forwards to another URL

### ISSUE THREAD

**Issue by fabtigger** [Desertsnowman/Caldera-Forms#382]
I just updated to the latest version of wordpress 4.4 yesterday. My website has been working fine until I did this. Now when someone sends a form the messages sends but goes to a blank displaying this info...

{"url":"https:\/\/www.mywebsite.com\/thank\/?page_id=8779&preview=true&cf_preview=CF55e96a4fa8f5c&cf_id=502","result":"Redirecting","data":{"page_id":"8779","preview":"true","cf_preview":"CF55e96a4fa8f5c","cf_id":"502"},"html":"<div class=\" alert alert-success\">Redirecting<\/div>","type":"complete","form_id":"CF55e96a4fa8f5c","form_name":"testing form","status":"complete"}

How do I fix this please, even if its just a forced redirect url 

Luke

**Comment by Shelob9** [comment]
Can you please enable WP_DEBUG and try again?

**Comment by fabtigger** [comment]
Hello Josh.

Thanks for getting back to me quickly. This is on a live website so is hard
to debug. The website is on a secured server so perhaps this might be
contributing to the error? Please don't post this online as it has urls
that I don't want online...


regards

Luke

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: register_sidebar was called *incorrectly*. No id was set in the
arguments array for the "Sidebar 1" sidebar. Defaulting to "sidebar-1".
Manually set the id to "sidebar-1" to silence this notice and keep existing
sidebar content. Please see Debugging in WordPress
<https://codex.wordpress.org/Debugging_in_WordPress> for more information.
(This message was added in version 4.2.0.) in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3787*

*Notice*: The called constructor method for WP_Widget is *deprecated* since
version 4.3.0! Use

__construct()

instead. in */home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3619*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*
[image: Serviced Apartments in Central London – Mayfair, Kensington,
Belgravia, Bayswater, Knightsbridge]
<https://www.maykenbel.com/cc-form/%3Cbr%20/%3E%3Cb%3ENotice%3C/b%3E:%20%20force_ssl_login%20is%20%3Cstrong%3Edeprecated%3C/strong%3E%20since%20version%204.4!%20Use%20force_ssl_admin()%20instead.%20in%20%3Cb%3E/home/maykenbel.com/public_html/wp-includes/functions.php%3C/b%3E%20on%20line%20%3Cb%3E3568%3C/b%3E%3Cbr%20/%3Ehttps://www.maykenbel.com>
   Talk to us today    +44(0)20 3758 7255 <02037587255>
               Select Language               中文 (Chinese)
8AM-8PM WEEKDAYS + 9AM-4PM SATURDAYS (UK)

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

   - HOME <https://www.maykenbel.com/>
   - OUR APARTMENTS <https://www.maykenbel.com/our-apartments/>
      -
         - [image: small butteryfly]
         <https://www.maykenbel.com/our-apartments/>
            - <https://www.maykenbel.com/kensington-apartments/>
               -
               <https://www.maykenbel.com/apartments/130-queens-gate-apartments-in-kensington/>
               - <https://www.maykenbel.com/apartments/queensgate-court/>
               - <https://www.maykenbel.com/apartments/manson-place/>
               -
               <https://www.maykenbel.com/apartments/ashburn-court-serviced-apartments-in-kensington/>
            - <https://www.maykenbel.com/mayfair-apartments/>
               -
               <https://www.maykenbel.com/apartments/mayfair-house-apartments-in-mayfair/>
               - <https://www.maykenbel.com/apartments/17-hertford-street/>
               - <https://www.maykenbel.com/apartments/20-hertford-street/>
            - <https://www.maykenbel.com/knightsbridge-apartments/>
               - <https://www.maykenbel.com/apartments/chesham-court/>
               -
               <https://www.maykenbel.com/apartments/claverley-court-apartments-in-knightsbridge/>
            - <https://www.maykenbel.com/bayswater-apartments/>
               - <https://www.maykenbel.com/apartments/fountain-house/>
               - <https://www.maykenbel.com/apartments/chilworth-court/>
            - [image: small butteryfly]
         <https://www.maykenbel.com/our-apartments/?penth_enabled=1&hidden_enabled=1>
         - [image: small butteryfly]
         <https://www.maykenbel.com/hotels/ashburn-kensington/>
      - ENQUIRIES <https://www.maykenbel.com/enquiries-2/>
   - CORPORATE <https://www.maykenbel.com/corporate-apartments-london/>
      - <https://www.maykenbel.com/corporate-apartments-london/>
      - <https://www.maykenbel.com/corp-nttp/>
      - <https://www.maykenbel.com/travel-information/>
   - OFFERS <https://www.maykenbel.com/apartment-promotions-london/>
   - BLOG <https://www.maykenbel.com/london-life/>
      -
         -























         [image: Cycle Revolution - Design Museum]
         <https://www.maykenbel.com/cycle-revolution-design-museum/>
         <https://www.maykenbel.com/cycle-revolution-design-museum/>
         <https://www.maykenbel.com/cycle-revolution-design-museum/>
         [image: What's on in London - December 2015]
         <https://www.maykenbel.com/whats-on-in-london-december-2015/>
         <https://www.maykenbel.com/whats-on-in-london-december-2015/>
         <https://www.maykenbel.com/whats-on-in-london-december-2015/>
         [image: What's on in London - November 2015]
         <https://www.maykenbel.com/whats-on-in-london-november-2015/>
         <https://www.maykenbel.com/whats-on-in-london-november-2015/>
         <https://www.maykenbel.com/whats-on-in-london-november-2015/>
         -
      <https://www.maykenbel.com/london-life/>
      - ABOUT <https://www.maykenbel.com/about-us/>
      -
         - [image: small butteryfly] <https://www.maykenbel.com/about-us/>
            - [image: maykenbel-small-logo2]
            <https://www.maykenbel.com/about-us/>
            - [image: Serviced apartments in south Kensington]
            <https://www.maykenbel.com/why-choose-us/>
            - [image: london serviced apartments - bedroom]
            <https://www.maykenbel.com/our-reservations-team/>
         - [image: small butteryfly] <https://www.maykenbel.com/services/>
         - [image: small butteryfly] <https://www.maykenbel.com/cc-form/#>



Credit Card Form

*Notice*: force_ssl_login is *deprecated* since version 4.4! Use
force_ssl_admin() instead. in
*/home/maykenbel.com/public_html/wp-includes/functions.php
<http://maykenbel.com/public_html/wp-includes/functions.php>* on line *3568*

Thank you for choos­ing Mayken­bel Prop­er­ties. Please com­plete the form
below with your name, address, and pay­ment details.
*Please note:* your reser­va­tion remains sub­ject to avail­abil­ity until
your pay­ment details have been sub­mit­ted.

Fields marked with * are required.

Property *
  130 Queens Gate  Mayfair House  Manson Place  Fountain House  Claverley
Court  Ashburn Court  Queensgate Court  Chilworth Court  Chesham Court  17
Hertford Street  20 Hertford Street  Princes Square
Check-in Date *
Check-out Date *
Num­ber of Adults *
  1  2  3  4  5  6  7  8
Num­ber of Chil­dren *
  0  1  2  3  4  5
This book­ing is... *
  ...for myself   ...on behalf of some­body else
Title *
  Mr  Miss  Mrs  Ms  Dr  Prof
First Name *
Last Name *
Email *
Company Name
Name on Card *
Card Type *
  Please Select...  Visa  Mastercard  American Express  Switch/Maestro
Card Number *
Secu­rity Code *
Card Start Date
Card Expiry Date *
Issue Number
Address 1 *
Address 2
City *
Country *
Zip / Post Code *
Phone Number *
Anti Spam *
8 - 4 =
Terms & Con­di­tions *
 I’ve read and agree with the Terms & Con­di­tions? (Below)

Please read the terms and con­di­tions here
<https://www.maykenbel.com/ts-cs/>.







On Tue, Jan 5, 2016 at 12:42 PM, Josh Pollock <notifications@github.com>
wrote:

> Can you please enable WP_DEBUG and try again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Desertsnowman/Caldera-Forms/issues/382#issuecomment-168989204>
> .
>



-- 
txt2nite.com, txt2nite®

**Comment by Desertsnowman** [comment]
Interesting. You say this goes to a blank page? not an ajax submission?

**Comment by fabtigger** [comment]
Sorry not a blank page, a white page with the  code below at the top of the page. 

If I uncheck "Enable Ajax Submissions. (No page reloads)", the form blanks after submission but does not forward to my thankyou page url. In both cases the form does successfully send an email.

Regards

{"url":"https:\/\/www.mywebsite.com\/thank\/?page_id=8779&preview=true&cf_preview=CF55e96a4fa8f5c&cf_id=502","result":"Redirecting","data":{"page_id":"8779","preview":"true","cf_preview":"CF55e96a4fa8f5c","cf_id":"502"},"html":"

Redirecting<\/div>","type":"complete","form_id":"CF55e96a4fa8f5c","form_name":"testing form","status":"complete"}

**Comment by Shelob9** [comment]
We don't use `force_ssl_login()` and I fixed the WP_Widget issue a few versions back. So, I can't say for certain, but this is most likely a conflict of some other plugin, not CF itself. Try disabling all other plugins and switching to the default theme to see if that resolves the issue. A quick search in your content directory for the deprecated function should turn up the culprit.
