### ISSUE TITLE
Beta gets automatically installed if using Github updater plugin

### ISSUE THREAD

**Issue by lmartins** [Desertsnowman/Caldera-Forms#384]
I was using Github updater for a different goal and Caldera got automatically updated, without warning, to a beta version which broke the site, again without warning.
I do recall seeing a note about compatibility with Github updater being added, wasn't aware it would update automatically Caldera to an unstable release. Maybe something you want to reconsider.

Cheers.

**Comment by Shelob9** [comment]
Nice catch @lmartins I'll look into this.

**Comment by timjrye** [comment]
I have the same issue. The version of the plugin in the WP.org repository has the 'GitHub Branch' in the plugin header set to 'current-dev'. As far as I can tell it should be set to 'current-stable'. See https://github.com/afragen/github-updater#hosting-plugin-in-wporg-repository.

**Comment by Shelob9** [comment]
Close via 37181aa
