### ISSUE TITLE
"Pin to Menu" doesn't use the role for exporting.

### ISSUE THREAD

**Issue by Desertsnowman** [Desertsnowman/Caldera-Forms#389]
When pinning a form to a menu for a specified role, the export entries still uses the admin permission check. Needs to use the pin setting to ensure full operation of the entry viewer.

**Comment by Shelob9** [comment]
Fixed via 98b5eff

@Desertsnowman Note that new method in admin class `save_form_cap_filter` only handles entry export, but it is set up to handle all types of interactions in the `save_form()` method if we want to.
