### ISSUE TITLE
Conditional in button field syntax is not compatible pre-5.5

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#392]

**Comment by Shelob9** [comment]
Issue is this line: https://github.com/Desertsnowman/Caldera-Forms/blob/current-stable/fields/button/field.php#L44

Change happened here: https://github.com/Desertsnowman/Caldera-Forms/commit/854d1bbb97f5fcc7616e69d5d1723873f0e807e0

**Comment by Shelob9** [comment]
@Desertsnowman Should this be `	if( !empty( $form['grid_object'] ) && is_object( $form['grid_object'] ) ){` IE Did you just miss the close of `empty` before the and or was the intent different?

**Comment by Desertsnowman** [comment]
yup
