### ISSUE TITLE
HTML field uses self keyword outside of object context

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#396]
Even if I'm wrong here, it smells wrong.

https://github.com/Desertsnowman/Caldera-Forms/blob/current-stable/fields/html/field.php#L79

**Comment by Shelob9** [comment]
A quick search shows this is pretty common. It is technically correct, beacuse these files are included inside of `Caldera_Forms::render_field()` but that there is no way to prevent them from being used in another context, in which the `self` keyword will be wrong. Also, it looks wrong. It's confusing to read ...

**Comment by Desertsnowman** [comment]
You are right. This is in external file and should not reference self

**Comment by Desertsnowman** [comment]
Also in Range slider, gravatar and calculator.
