### ISSUE TITLE
calculations not working after upgrade to 1.3.2

### ISSUE THREAD

**Issue by bsusala** [Desertsnowman/Caldera-Forms#397]
After upgrading to 1.3.2, calculation field(s) are not working anymore. Exported json, deleted plugin, fresh install, import, same. Deactivated all plugins but CalderaWP, still not working. Rechecked formulas, fields etc., still not. WP 4.4.1

**Comment by Desertsnowman** [comment]
Can you link the export here for me to test?

**Comment by bsusala** [comment]
I'd rather send it to you in a PM, if it's possible.

**Comment by bsusala** [comment]
I've stripped down the form, see attached.
[form.zip](https://github.com/Desertsnowman/Caldera-Forms/files/96632/form.zip)

**Comment by Desertsnowman** [comment]
@bsusala - thats perfect. I'll take a look this morning and see what I can do. thanks.

**Comment by Desertsnowman** [comment]
@bsusala - can you email me the exact export to david@caldera.co.za ?

**Comment by bsusala** [comment]
sent

**Comment by traveler-palm** [comment]
As you requested Josh -

 	Thank you for a great form solution,
…but the latest upgrade Version: 1.3.2 -
Failure in Calculation fields - they do NOT calculate
I am on WP 4.3.1
In case you need this…

### Environment ###

Home URL : http://thailandproject.asia/wordpress
Site URL : http://thailandproject.asia/wordpress
WP Version : 4.3.1
WP Multisite Enabled : No
Web Server Info : Microsoft-IIS/8.5
PHP Version : 5.5.31
MySQL Version : 5.1.73
WP Debug Mode : No
WP Language : en_US
PHP Post Max Size : 8M
WP Max Upload Size : 8 MB
WP Remote Post : Success
PHP Max Script Execute Time :0s
PHP Max Input Vars : 1000
SUHOSIN Installed" : No
Default Timezone : Default timezone is UTC
Operating System : WINNT (32 Bit)
Memory usage : 6.6 MByte
SQL Mode : Not set
PHP Safe Mode : 5.5.31
PHP Allow URL fopen : Off
PHP Memory Limit : 256M
PHP Max Post Size : 8M
PCRE Backtracking Limit :1000000
PHP Exif support : No
PHP IPTC support : Yes
PHP XML support : Yes

### Plugins ###

Installed Plugins : All-in-One Event Calendar by Time.ly by Time.ly Network Inc. version 2.3.7Backup by Sygnoos version 2.7.7Caldera Forms by David Cramer version 1.3.2Google Maps Easy by supsystic.com version 1.4.6Insert Pages by Paul Ryan version 3.1.1Simple Wp Sitemap by Webbjocke version 1.1.1TablePress by Tobias Bäthge version 1.7Verify Email for Caldera Forms by David Cramer for CalderaWP LLC version 1.0.1WP Backup Bank by Tech Banker version 1.0.14Wp Cleanup Optimizer Lite Edition by Tech Banker version 2.0.69Wp Mail Bank by Tech Banker version 1.35WP Sticky Menu by PTHEME version 1.0.0ZZ Image Slider by zudikas zveris version 1.3.1

### Themes ###

Theme Name : Cerauno
Theme Version : 1.0.1
Author URL : http://wordpress.com/themes/

**Comment by bsusala** [comment]
Temporary solution: I downgraded to 1.3.1.2 and my form seems to work without problems, email notifs receiving etc. I did not changed anything in my install.

**Comment by traveler-palm** [comment]
Josh, It may be a simple OFFSET problem in the "on-submit" processing, BEFORE STORING TO THE TABLE

e.g., 
1. SLIDER field returns not the value, but the Relative Position of the value.
     i.e. from possible values of 0-n, value 2 on slider returns 3 into the DBtable.

2. RADAR field returns not the value, but the Label into the DBtable.

That would explain the loss of calculation ability - the value returned is always 0.
(LABEL + LABEL + LABEL = 0)

**Comment by traveler-palm** [comment]
I also reverted to 1.3.1.2
All working fine again

**Comment by Desertsnowman** [comment]
I I think I discovered the problem, Are you all experiencing the problem when using Manual Calculations?

**Comment by traveler-palm** [comment]
Both Manual and Group, 
plus see above…
It may be a simple OFFSET problem in the "on-submit" processing, BEFORE STORING TO THE TABLE

e.g., 
1. SLIDER field returns not the value, but the Relative Position of the value.
i.e. from possible values of 0-n, value 2 on slider returns 3 into the DBtable.

RADIO field returns not the value, but the Label into the DBtable.
That would explain the loss of calculation ability - the value returned is always 0.
(LABEL + LABEL + LABEL = 0)

**Comment by bsusala** [comment]
Both manual and with operations.

**Comment by Desertsnowman** [comment]
Found the problem.
All cases contain checkboxes within the equation - sorting it out.

**Comment by Desertsnowman** [comment]
@bsusala - can you get the current-dev version and test it to see if it solves your problem?

**Comment by bsusala** [comment]
Yes it does! All ok now.

**Comment by Desertsnowman** [comment]
Great!
Fixed with v1.3.2.1
