### ISSUE TITLE
CSS Styles conflict with Layers WP

### ISSUE THREAD

**Issue by brandbrilliance** [Desertsnowman/Caldera-Forms#399]
When editing Caldera Forms, the edit and column icons are overridden to be the Layers icons, when Layers WP Theme Page Builder is installed.

![layerswp-conflic](https://cloud.githubusercontent.com/assets/1362479/12448818/54a48996-bf81-11e5-9db7-d96f8134dacc.jpg)

**Comment by brandbrilliance** [comment]
Looks like this might be a layers issue, as their CSS is loading for non-Layers admin screens.

**Comment by Desertsnowman** [comment]
A plugin should never included style willy-nilly. They should only be included on screens where they are used. I would understand if this screen was, say, a custom post type, which is a shared screen. But  this is a custom admin page. 
So yes, they need to fix their bug.
