### ISSUE TITLE
New Element: Tabular Data

### ISSUE THREAD

**Issue by bsusala** [Desertsnowman/Caldera-Forms#403]
In the spirit of drag and drop easy creation, it may be useful to have a Element of Tabular Data. Of course, this is achievable with HTML+%slug%+BS, but this new element will speed up things.

**Comment by Desertsnowman** [comment]
I was considering making a few HTML based elements, however I decided not to since it starts moving outside of the realm of form creation.

I appreciate the ideas though! I may use these for another plugin in time, so nothing goes to waste.
