### ISSUE TITLE
AJAX Submission with Ugly Permalinks Often Redirect To Response JSON

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#404]
Probably caused by fe8f20b2cd28d0c9cafc7f6c49ea0a0b8b8b96a5

Pretty sure that if the if the AJAX fail happens then instead when AJAX fail is triggered of submitting and refreshing page, you just see the response JSON.

I can't find any 100% reliable way to do this besides enabling turning on pretty permalinks and then preview a form. The preview url uses ugly permalinks, which causes AJAX submissions to fail (secondary issue). When you submit, the right URL is loaded, but only has response JSON.

![screen shot 2016-01-24 at 3 33 57 pm](https://cloud.githubusercontent.com/assets/1994311/12538750/f9eabb38-c2af-11e5-8063-35c26515c928.png)

**Comment by Desertsnowman** [comment]
I find it humorous that the issue number is 404

**Comment by Shelob9** [comment]
Closing beacuse #483 is the root cause and is about to be fixed #483
