### ISSUE TITLE
EDIT ENTRY malfunction in Admin 

### ISSUE THREAD

**Issue by traveler-palm** [Desertsnowman/Caldera-Forms#415]
V1.3.2.1, WordPress 4.3.1
In page wordpress/wp-admin/**admin.php?page=caldera-forms**
after entering with the **View** button
the  **Edit Entry** offering returns an empty list…
Result:
Editing Entry #498
Save Changes View Entry

**Comment by Desertsnowman** [comment]
thanks, will take another look to see if I can find a bug.

**Comment by traveler-palm** [comment]
The problem appears to have disappeared @Desertsnowman.
My environment remains unchanged from my end, but I can't speak for my host.
It's working, for the moment, so don't bother to chase it. Thank you.

**Comment by Desertsnowman** [comment]
Did your site by any chance get updated to 4.4.2 recently?

**Comment by traveler-palm** [comment]
I'm still on 4.3.1.  Updates are my responsibility.
System status:
Site URL :http://thailandproject.asia/wordpress
WP Version :4.3.1
WP Multisite Enabled :No
Web Server Info :Microsoft-IIS/8.5
PHP Version :5.5.31
MySQL Version :5.1.73
WP Debug Mode :No
WP Language :en_US
PHP Post Max Size :8M
WP Max Upload Size :8 MB
WP Remote Post :Success
PHP Max Script Execute Time :60s
PHP Max Input Vars :1000
SUHOSIN Installed :No
Default Timezone :Default timezone is UTC
Operating System :WINNT (32 Bit)
Memory usage :7.53 MByte
SQL Mode :Not set
PHP Safe Mode :5.5.31
PHP Allow URL fopen :Off
PHP Memory Limit :256M
PHP Max Post Size :8M
PCRE Backtracking Limit :1000000
PHP Exif support :No
PHP IPTC support :Yes
PHP XML support :Yes

**Comment by Desertsnowman** [comment]
No idea. My only thinking is the permalink got reset which can solve loading issues.

**Comment by traveler-palm** [comment]
Thank you David. If it resurfaces, I’ll inform you.


Enjoy life,
Maxwell Stirling
Thailand Project
………
