### ISSUE TITLE
Forms do not respond to submission when a custom processor is used.

### ISSUE THREAD

**Issue by meyerg5m** [Desertsnowman/Caldera-Forms#416]
When you configure a form to use a custom processor it will no longer respond to submission, ie the success message does not display and the form does not hide.

**Comment by Desertsnowman** [comment]
Hi There,

Would it be possible to email me the processor so I can take a look at what the issue may be?
email david@caldera.co.za

**Comment by meyerg5m** [comment]
Many thanks for the reply but it's now solved - there was a 'die' in the plugin which was stopping the form from acting normally.
