### ISSUE TITLE
Error submitting a file (doc, pdf, jpeg)

### ISSUE THREAD

**Issue by x-dana** [Desertsnowman/Caldera-Forms#421]
I've created a form with file submission (doc, pdf, jpeg) but when I try to upload one of these files I receive this message :-1: 

Warning: file_get_contents(/home/content/98/8407498/html/lenterstudio/rear//rear/wp-content/uploads/2016/02/11707703_10206218847523828_5626185239424524667_n5.jpg): failed to open stream: No such file or directory in /home/content/98/8407498/html/lenterstudio/rear/wp-content/plugins/contact-form-7-to-database-extension/CF7DBPlugin.phpon line 729
{"result":"Abbiamo ricevuto la tua candidatura. Grazie.","data":{"cf_id":"30"},"html":"
Abbiamo ricevuto la tua candidatura. Grazie.<\/div>","type":"complete","form_id":"CF569786b9517db","form_name":"Prova Lavora con noi","status":"complete"}

Don't know why it reads with the double /
lenterstudio/**rear//rear**/wp-content

**Comment by Shelob9** [comment]
This isn't a bug in Caldera Forms, it's in the contact-form-7-to-database-extension plugin. Saving to database is a free feature of Caldera Forms anyway.
