### ISSUE TITLE
Extend tab is borked 

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#423]
API request returns:
`{"_render_time":0.0918,"_version":"1.0","code":200,"message":"OK","channels":[{"channel":"extensions","location":"marketing\/extensions","name":"Extensions","attributes":"data-autoload=\"true\""},{"channel":"featuredextensions","location":"marketing\/featured","name":"Featured","attributes":"style=\"font-weight:bold;\""}]}`

Unless this is an easy fix, I say we replace it with link to https://calderawp.com/caldera-forms-add-ons/ as a quick fix until we switch over to Freemius.

**Comment by Desertsnowman** [comment]
did anything change on the API endpoint on CWP?

**Comment by Shelob9** [comment]
Fixed here: https://github.com/CalderaWP/calderawp-api/commit/9b8b0bcaaa3361939098a17a5379a76b55958714
