### ISSUE TITLE
In fields JS change name of variable `prevalidator` to something without `eval` in it.

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#424]
Related #414

Best theory I have as to why fields.min.js is getting flaged as a security conceren is it contains the word `eval`. Let's just change `prevalidator` to `precheck` or something.

https://github.com/Desertsnowman/Caldera-Forms/blob/current-stable/assets/js/fields.min.js

**Comment by Desertsnowman** [comment]
fixed in 29402b6

**Comment by Shelob9** [comment]
@Desertsnowman Can you please commit the non-minifed version of assets/js/fields.min.js ?

**Comment by Desertsnowman** [comment]
@Shelob9 its a compiled version of all JS for the fields. the source files are in each field-type folder.
I will make a grunt task to do the compiling

**Comment by Shelob9** [comment]
I see....
