### ISSUE TITLE
Only one attachment of a multi-select image field gets attached to mailer

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#429]

**Comment by dchacons** [comment]
Hi, some extra info: Yes, all the files are uploaded to the server succesfully, and inside the e-mail i got all the urls for those images, but inside the e-mail body only ONE image is attached. All the "file upload" variables of the form has the "attach to mail" check box, checked. So if I want to download those images, I have to access each server URL and download it one by one.

Calder-Forms version: v1.3.2.1
WordPress version: v4.4.2

**Comment by dchacons** [comment]
Hi I want to ask about this bug and if going to be fix on next releases, thanks

**Comment by Shelob9** [comment]
Close via 2bd5b7f

**Comment by dchacons** [comment]
The problem continues in the new version 1.3.4 I open this new issue wih more info: #504 

Thanks for all your work

**Comment by Desertsnowman** [comment]
@dchacons this is not really related to #504 since this refers to a single file field set as multiple. The new issue is multiple file fields.

**Comment by dchacons** [comment]
Thanks no problem, I was the one that opnened #429 for the same reason, maybe I don't explain myself the first time :P

**Comment by Shelob9** [comment]
@dchacons That or I didn't understand. I have it on tomorrow's TODO list, hopefully we can have a gix for that soon.
