### ISSUE TITLE
Problem on export

### ISSUE THREAD

**Issue by lipaonline** [Desertsnowman/Caldera-Forms#433]
Hello,
i have a checkbox, when i check only one item, an error appaires en export:

> <b>Notice</b>: Undefined offset: 0 in <b>/var/www/clients/client2/web2/wp-content/plugins/caldera-forms/classes/admin.php</b> on line <b>1434</b>

if i comment this line :
`elseif( is_array( $row[$key] ) && count( $row[$key] ) === 1 )$row[$key] = $row[$key][0];}`

everything working fine.

I don't understand why you added this test ?

Best regards
Patrick

**Comment by Desertsnowman** [comment]
been sorted in a previous commit.
