### ISSUE TITLE
Steel something wrong with validaiton mask in ver.1.3.3.1

### ISSUE THREAD

**Issue by zikkod** [Desertsnowman/Caldera-Forms#445]
I've just tested phone validation. It allows to use local, international and custom mask. I changed custom to e.g. (___)___-__-__ but it has been updated only in Editor default value field. In a real page form the old defaul mask remained like (___ )___-____ . If to use a placeholder it's become very odd. i.e. placeholder is shown as new (___)___-__-__ but at hover it's being changed to default  (___ )___-____ That's confuses. Anyway the plugin is superb!

**Comment by Desertsnowman** [comment]
I have had issues with the phone field. if you need more control, use a single line text field and enable masked input. this will allow you much greater flexibility.

**Comment by zikkod** [comment]
Many thanks! I'll try.
