### ISSUE TITLE
sync field values

### ISSUE THREAD

**Issue by Desertsnowman** [Desertsnowman/Caldera-Forms#455]
in a text field, setting the default to `%another_field_slug%` will allow it to get the value typed in the other field live.
typing in the synced field, will stop binding and use the user entered value. 
Hard to explain. see anim example:
![syncfields](https://cloud.githubusercontent.com/assets/307466/13661147/bc10d97a-e698-11e5-9c25-3aa4e1e4f82d.gif)

**Comment by Shelob9** [comment]
Close via 		600783c

**Comment by Shelob9** [comment]
I am reopening. In current build the synced field keeps reverting back to the main field's value... @Desertsnowman please double check.

**Comment by Desertsnowman** [comment]
closed via  2487dd3

**Comment by Shelob9** [comment]
https://calderaforms.com/doc/field-sync/
