### ISSUE TITLE
Magic Tags not applied to checkbox labels when the value/label are defined separately.

### ISSUE THREAD

**Issue by dwithnall** [Desertsnowman/Caldera-Forms#457]
To replicate create a variable in your form.
```
Name: test
Value: blah
Behaviour: static
```
Insert a checkbox element to the form, add an option and tick the box **Show Values**

Add the variable to the value & label fields for the option
{variable:test}

Upon rendering the checkbox Value correctly interprets the variable, however the Label does not.

The issue is that when show values is disabled format_select_options() /classes/core.php line #1737 sets 
```
$option[ 'value' ] = $option[ 'label' ] = self::do_magic_tags( $option[ 'label' ] );
```

However if show values is enabled 
```
$option[ 'value' ] = self::do_magic_tags( $option[ 'value' ] );
```

I just added the following line to enable magic tags on values
```
$option[ 'label' ] = self::do_magic_tags( $option[ 'label' ] );
```

Kind regards,

Dave.

**Comment by Shelob9** [comment]
Using latest beta, the variable isn't interpreted in front-end. 

@Desertsnowman can you either fix or provide a workaround, as I'm not sure that is actually supported?
![screen shot 2016-03-25 at 1 31 35 am](https://cloud.githubusercontent.com/assets/1994311/14038597/57254478-f229-11e5-8f3a-8aeef51c2d2e.png)
