### ISSUE TITLE
"File upload" field Should allow adding to selection

### ISSUE THREAD

**Issue by antowp** [Desertsnowman/Caldera-Forms#462]
Hello,

"File upload" can upload only one image, even I selected "multiple image".
I am trying Caldera 1.3.3.1 + its free add-ons.

Thank you.

**Comment by Shelob9** [comment]
This is a duplicate of #446

**Comment by Shelob9** [comment]
This is not a duplicate of #446 I am renaming it to clarify a bit. It can upload multiple files, but they have to both come up in same dialog. You can't add another one.

**Comment by Shelob9** [comment]
"fixing" this would require using one of those close JS libraries for multi-file uploads, since the normal uploader doesn't support this. @Desertsnowman When you need a fun challenge, add an "advanced file field"

**Comment by Shelob9** [comment]
@Desertsnowman Please make into a "Advanced File Field" leave existing as-is.
