### ISSUE TITLE
Unable to save while visual editor access is disabled

### ISSUE THREAD

**Issue by nerdworker** [Desertsnowman/Caldera-Forms#472]
Had an issue where a processor would not save changes. Finally found an old support issue from a year ago about a similar issue where they had the backend admin editor disabled and had to reenable it to successfully save changes ([https://wordpress.org/support/topic/suddenly-the-forms-are-not-being-saved]). When we tried it, it worked for us as well. So, this is still an issue.

**Comment by Shelob9** [comment]
I can't reproduce this issue. I'm going to assume that WP Fastest Cache (mentioned in original post) or some other plugin is checking the meta key that option sets and putting in a security check, or caching our API.
