### ISSUE TITLE
Conditional logic vanishing in multipage form

### ISSUE THREAD

**Issue by Steph-189** [Desertsnowman/Caldera-Forms#473]
I created a 5 page form. The form is very interactive. The last 4 pages in the form have conditional logic setup. Up until 2 days ago, it worked fine. Then yesterday, I attempted to update just some text and updated the form. I left the form and then went back to it. When I went to test it out, all of the conditional logic vanished. When I logged back into my editor to view this form, there were no conditions set. So I reset them all again. Closed the editor out and the form worked. Had to make a few more small adjustments, updated the form and the conditions again had been erased. This continues to happen each time I log out or leave this form after updating. The set conditions appear to remain in place invisibly until I update the form then the are completely gone and again need reset. I have not received any specific errors for this. Now a new issue has occurred incidental of this. All of the spacing fields I placed in my form are not working but were earlier. I am using both the most updated version of WordPress and most updated Caldera Forms. I am a non-tech user so I rely on the simplicity of this plug-in. Any ideas as to how to correct this? I wonder if I just need to abandon this form and rebuild from the ground up? When it worked 2 days ago, it worked great.

**Comment by Desertsnowman** [comment]
should be sorted via 767f6764b24dde8ae34945d0a9382dd616a71041
