### ISSUE TITLE
Caldera Forms Version 1.3.3.1 - Does not submit in IE11.0 unless non-required field exists

### ISSUE THREAD

**Issue by alfpet** [Desertsnowman/Caldera-Forms#478]
Hello 

I have found he following unexpended behaviour (bug) with Caldera Forms Version 1.3.3.1:

Example form:
First Name
Last Name
Email
re-Captcha

First Name, Last Name and Email are set to be required.

This form can be submitted without problems in Chrome but will not submit in IE11.0. No error message - just no action.

Making one of the fields (Last Name) not required results in the form being submitted in IE11.0 as well.

Please advise on how to resolve this issue.

Many thanks in advance

**Comment by Shelob9** [comment]
Can you please try removing the recaptcha field and see if that fixes the issue?

**Comment by Shelob9** [comment]
Closing this as we have no heard back in over two weeks
