### ISSUE TITLE
Importing a form doesn't redirect to new form

### ISSUE THREAD

**Issue by Desertsnowman** [Desertsnowman/Caldera-Forms#499]
possibly related to #466 or #483

**Comment by Shelob9** [comment]
@Desertsnowman I can't reproduce this with latest version and a valid file. Are you sure that the db update ran for you?

**Comment by Desertsnowman** [comment]
No not sure. Which is also a problem then. I'm on mobile so can't test. But can you install the current version then switch to new version and see if that I'd truly the issue?

**Comment by Shelob9** [comment]
Good point. I `delete_option( '_caldera_forms' ); delete_option( '_caldera_forms_forms' ); delete_option( 'CF_DB' );` role back to 1.3.3.1 - I make form - I export form - I import -- it imports and redirects...

I think you might have missed the updater. Yes, that worries me, hence why I'm not skipping #492

**Comment by Desertsnowman** [comment]
Issue is the redirect sending 200 status and needs 302

**Comment by Desertsnowman** [comment]
Closed via 6fccfb2
