### ISSUE TITLE
Fatal error: Can't use function return value in write context in /.../core.php on line 496

### ISSUE THREAD

**Issue by zoomwebstudio** [Desertsnowman/Caldera-Forms#50]
Hello,
I try to activate the user registration plugins and I get always this error : 

Fatal error: Can't use function return value in write context in /home/getd/public_html/tg/wp-content/plugins/cf-users/core.php on line 496

How can I do

**Comment by kartcon** [comment]
David,
I have also seen this issue lately. What I get is:
Fatal error: Function name must be a string in /home/aprweb/public_html/WordPress/wp-content/plugins/caldera-forms/classes/core.php on line 1879

I am using WordPress version 4.1 running Weaver II theme. My version of CF is 1.1.9.3. PHP ver 5.4
I can tell you that the form data does get written to the database, but seems to fail later, possibly when generating the email. If I submit the form I do receive the 'user' email confirmation, but never get the 'admin' confirmation with the form data. I also have Shortcodes Ultimate v 4.9.3 (I think I read there may be an issue with this plug-in, but really can't disable or delete it at this time)

Hope this help. Thanks,
Art (kartcon)

**Comment by pippinsplugins** [comment]
Usually this happens when a function (such as `get_the_title()`) is used inside of `empty()`. I've looked through the entire `core.php` file but don't see anywhere that's being done.

I'd guess that this has been fixed at some point.

**Comment by Desertsnowman** [comment]
This is in the users addon. It has been fixed. Thanks for pointing out I need to close things.
