### ISSUE TITLE
Even do multiple files are attached to the form only one is attached to mail 1.3.4

### ISSUE THREAD

**Issue by dchacons** [Desertsnowman/Caldera-Forms#504]
(Even do multiple files are attached to the form only one is attached to mail).

Hi, thanks for all your work, keep going.

I noticed that in the new update (1.3.4) the problem with multiple images attached to mail continues, I show you the problem with images:

**FORM: (3 images attached)**

![selected images](https://cloud.githubusercontent.com/assets/17337158/14143658/ae90c7f4-f649-11e5-99c2-5acc6749142e.JPG)

**MAIL: (only 1 image attached to mail, even do the 3 images where uploaded to the server)**

![only one image attached on mail](https://cloud.githubusercontent.com/assets/17337158/14143656/ae7f2fe4-f649-11e5-8bed-7c209a7ab32b.JPG)

**Attach to mail checked for all images:**

![attach to mail option checked for all photos](https://cloud.githubusercontent.com/assets/17337158/14143657/ae7f4772-f649-11e5-8b30-29c52f9ce9e2.JPG)

**Caldera Form version:**

![1-3-4 version](https://cloud.githubusercontent.com/assets/17337158/14143655/ae7f041a-f649-11e5-89ed-e8a6b18a35d1.JPG)

Thanks for all

**Comment by Shelob9** [comment]
This is a new issue, not #429  
#429 related to one field with multiple files uploaded, this is multiple file fields in same form. I suspect what I did for #429 will is causing this. We will fix in 1.3.5

**Comment by Desertsnowman** [comment]
Correction, fixed now :)

**Comment by dchacons** [comment]
Great job, I will be waiting for next release with this fix, thank you

**Comment by Desertsnowman** [comment]
It's out now. Go get v 1.3.4.2
