### ISSUE TITLE
Josh left a fucking annonymous function in main class constructor

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#506]

**Comment by Desertsnowman** [comment]
didn't want to say anything. but... -10 for that one.

**Comment by Desertsnowman** [comment]
+3 for admitting it.

**Comment by Desertsnowman** [comment]
and -2 for @Desertsnowman for not picking it up in my testing

**Comment by wpappdev** [comment]
Finally, a +100 to the both of you for your continued work on this awesome plugin. Thank you!

**Comment by Shelob9** [comment]
@wpappdev +5 to you for being so supportive.

Also, welcome to Josh's game of arbitrary internet points :)

@Desertsnowman Did you just fix on dotORG svn, or did it make it back into the Git repo?

**Comment by Desertsnowman** [comment]
@Shelob9 both, although github is 1.3.4 not 1.3.4.1
