### ISSUE TITLE
Illegal offset when getting multi-select options for export or edit

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#508]
I don't see why it would happen, but I didn't validate that `$opt` could be not be a key of `$field_value`  `$field_value[ $opt ]`... But its happening. I guess the issue here is that if form config has changed, we could have a saved value on an option that no longer exists, maybe?

@Desertsnowman What do you think? Easy fix to prevent warning, but I think we could have a deeper issue here...

Example notice form user: `Warning: Illegal string offset 'opt1910719' in /wp-content/plugins/caldera-forms/classes/core.php on line 4040`

**Comment by tjievina** [comment]
The same thing is happening to me! I can't export or view entries.
I also received this warning when I click on 'Export'

Cannot modify header information - headers already sent by (output started at /home/achieversllc/public_html/wp-content/plugins/caldera-forms/classes/core.php:4040)

Please help!

**Comment by Shelob9** [comment]
Yah, `$field_value` is a string, not an array when no value is set for an option. -5 @shelob9

**Comment by Shelob9** [comment]
Should be fixed via 		3346667

@Desertsnowman Can you double check what I did here please: https://github.com/Desertsnowman/Caldera-Forms/blob/334666747e94c295b89a638f6cce0daecfa328fa/classes/core.php#L4034-L4041

That else statement makes me nervous. Pretty sure it will never be hit. If it does, we get nothing, but no error. Still.

**Comment by Desertsnowman** [comment]
@Shelob9 that will do it for now. can you pull it in?
