### ISSUE TITLE
shortcode atts check in Caldera_Forms:render_form() could unload form

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#510]
Check this out:

```
	if(empty($atts['id'])){
		if(!empty($atts['name'])){
			$form = self::get_form( $atts['name'] );
		}
	}elseif( !empty( $atts['id'] ) ){
		$form = self::get_form( $atts['id'] );
	}

``` 

If you pass a form config array with out a name saved, it's going to reload based on `'id'` not `ID` and fail.

**Comment by Shelob9** [comment]
Should be fixed via 	ae7a58c
Reassigning to @Desertsnowman  for review.

**Comment by Desertsnowman** [comment]
fine with me

**Comment by Desertsnowman** [comment]
@Shelob9 can you pull this in? I think I might break something.

**Comment by Shelob9** [comment]
issue/510 branch didn't merge cleanly - gitfail on Josh
I make new fix

**Comment by Shelob9** [comment]
Actually, somehow the fix is already in current-dev 

Closing as _um, OK, I guess, yah, I know how GIT works_
