### ISSUE TITLE
Any plans for Radio Image selection?

### ISSUE THREAD

**Issue by lmartins** [Desertsnowman/Caldera-Forms#516]
This might be a stretch, im not sure, but it seems to me quite useful for some situations, where the forms are used as a very simplified form of ordering process, allowing the user/customer to pick a selection from an image instead of just text.

**Comment by Desertsnowman** [comment]
I know exactly what you mean. I have in the past needed to do the same thing. 

However this is custom field type territory. I might in future make something like this but for now it's not supported.
