### ISSUE TITLE
Forms not submitting

### ISSUE THREAD

**Issue by jaimeadvantageousmediapartners** [Desertsnowman/Caldera-Forms#519]
Customers report that nothing happens when form is submitted: No error message. No Submission. Version 1.3.4.2, WP 4.4.2.  http://biz-e-book.com/bgclsc/be-a-part-bgclsc/order-form-bgclsc/

**Comment by Desertsnowman** [comment]
Do you have a caching plugin by any chance?

**Comment by jaimeadvantageousmediapartners** [comment]
WP Super Cache

**Comment by jaimeadvantageousmediapartners** [comment]
Yes, WP Super Cache. Forms are now submitting after I emptied all caches, thanks. Sorry for the newbie error…
