### ISSUE TITLE
Checkbox should not be required & No error color if there is no label

### ISSUE THREAD

**Issue by lefty55104** [Desertsnowman/Caldera-Forms#53]
I had a checkbox that was not required but had only one option but it seemed to need to be checked in order for the form's next/previous buttons to work. Since it is a checkbox, there shouldn't be a required value.

Also, unless the "hide label" box is unchecked, the text next to the checkbox does not turn red to indicate that the checkbox needs to be checked in order to proceed.

I'm not sure if this is the case with any other fields.

**Comment by Desertsnowman** [comment]
this sounds odd, I'll take a look and let you know. thanks.

p.s. sorry for the late reply.

**Comment by Desertsnowman** [comment]
sorted.
