### ISSUE TITLE
Blank page after pressing submit form button on a HTTPS website

### ISSUE THREAD

**Issue by BRC21** [Desertsnowman/Caldera-Forms#531]
Hi,
On a HTTP website, pressing the submit button of the form send to a new page indicating that the form has been returned. It's perfect.

However,  on HTTPS website, pressing the submit button of the form returns a blank page with the following code:
{"result":"Le formulaire a \u00e9t\u00e9 envoy\u00e9.\nA bient\u00f4t !","data":{"cf_id":"15"},"html":"<div class=\" alert alert-success\">Le formulaire a \u00e9t\u00e9 envoy\u00e9.\nA bient\u00f4t !<\/div>","type":"complete","form_id":"CF56e6d5df1b6a5","form_name":"Demande de devis gratuits","status":"complete"}.
On the adminitrator web side, the form has been received. Problem is blank page after pressing submit form button.

**Comment by Shelob9** [comment]
Can you try removing the special characters from your success message? Could be an issue with support for non-english charecters we missed.

**Comment by BRC21** [comment]
The problem was not HTTPS. I remove polyfiller.min.js from minification process of WP ROCKET extension. Now all is fine.
Thank you.
