### ISSUE TITLE
Has the Paypal Sandbox mode broken?

### ISSUE THREAD

**Issue by stefanmccall** [Desertsnowman/Caldera-Forms#532]
I've been trying to do some testing on a new form for a site I built last year. The Paypal Sandbox mode on the PayPal processor worked fine for me last November but now when I submit the form I get a brief spin of the form wheel and then it disappears and nothing happens. I've tried it with regular PayPal credentials and that works fine, I only have an issue when using a Sandbox account (I have checked the box for Sandbox mode and I the latest version of the form installed).

**Comment by Shelob9** [comment]
@stefanmccall Can you please submit a support request at https://CalderaWP.com/support and give us more details.

I'm closing this as it is not a Caldera Forms bug, but I'm happy to help via our support system.
