### ISSUE TITLE
I get the Script Error with forms!

### ISSUE THREAD

**Issue by farzam-parto** [Desertsnowman/Caldera-Forms#54]
Hi,
I have problem with one of my forms, I get this errors and after that some fields despaired! 
Here is errors:

Script: http://my-website/wp-content/plugins/caldera-forms/assets/js/admin.min.js?ver=1.1.9.2:2

Script: http://my-website/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,shortcode,plupload,json2,zxcvbn-async,thickbox,media-upload&ver=4.1:3

I have exported file of form also

**Comment by Desertsnowman** [comment]
I'm going to need more info on this. what is the exact error you get? is it in admin of front?

**Comment by Desertsnowman** [comment]
Asuming script error caused by another plugin or theme script.
