### ISSUE TITLE
Cannot edit entries

### ISSUE THREAD

**Issue by shermanoakschamber** [Desertsnowman/Caldera-Forms#543]
When I go into **view entry** and then **edit entry** to make any changes, there's no information or list. There's just a view entry or save changes button. 
This was working fine a couple of weeks ago but now it isn't. I think it's a bug. 

Can you please help?

Thank you!

**Comment by Shelob9** [comment]
This is a duplicate of #508 which has already been fixed. You can update to the latest beta (current-dev branch here) or wait for the update on dotOrg next week.

**Comment by shermanoakschamber** [comment]
Hi @Shelob9 , 
Thanks for the help! This is probably annoying so I apologize for the inconvenience but I'm new at this so I don't understand. Will the update be sent next week to my site like it usually is when an update is released and I just have to update it or is dotOrg something I need to find and make the update manually?  
Thank you!

**Comment by Shelob9** [comment]
@shermanoakschamber Sorry, by "dotOrg" I mean WordPress.org/plugins.

So yes, sometime next week we will release Caldera Forms 1.3.5 and this update will come through WordPress. If you want the fix right away, you grab the current-dev branch from here.

**Comment by shermanoakschamber** [comment]
Thank you, much appreciated!
