### ISSUE TITLE
Not able to edit forms - Blank forms on edit after update to WP 4.5

### ISSUE THREAD

**Issue by paaljoachim** [Desertsnowman/Caldera-Forms#550]
Hey

A client just contacted me in regards to not being able to edit any of the forms since they are blank.
![screen shot 2016-04-18 at 23 55 07](https://cloud.githubusercontent.com/assets/5323259/14621639/90ff0d10-05c4-11e6-902d-d6b4f78d5ece.png)

I just checked the Inspect element console which is showing this error:

![screen shot 2016-04-19 at 00 22 22](https://cloud.githubusercontent.com/assets/5323259/14621673/d5b67448-05c4-11e6-9d63-2b9e97e27742.png)

load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:9 JQMIGRATE: Migrate is installed, version 1.4.0
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:2 Uncaught Error: Syntax error, unrecognized expression: #cff-admin a[href*=#]:not([href=#])
load-scripts.php?c=1&load[]=jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,post…:642 Uncaught TypeError: Cannot read property 'hasClass' of undefined(anonymous function) @ load-scripts.php?c=1&load[]=jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,post…:642n.event.dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:3r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:3n.event.trigger @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:3a.event.trigger @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:9(anonymous function) @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:3n.extend.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:2n.fn.n.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:2n.fn.extend.trigger @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:3(anonymous function) @ load-scripts.php?c=1&load[]=jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,post…:641i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:2j.fireWith @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:2y @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:4c @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload,zxcvbn-async&ver=12c38119c84e…:4

**Comment by Shelob9** [comment]
@paaljoachim This is a pretty common issue with 4.5's update to jQuery, which used to allow the unsupported syntax that you see in that error. That said, we don't use it and that error doesn't originate from our plugin.

To get a more useful error that should show you which script has the problem, try reloading with `SCRIPT_DEBUG` defined as true. That way core will not combine scripts.

**Comment by paaljoachim** [comment]
Thank your quick response Josh!
I have the Custom Facebook Feed Pro plugin installed which is affecting the edit area of Caldera Forms. I will also contact the developer of the Facebook Feed plugin about this issue.
