### ISSUE TITLE
Error in editor

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#553]
I've seen this before, and I don't want to release until we can address it. If I import the form @Desertsnowman put in #551 then I get:
`edit.min.js:1 Uncaught TypeError: Cannot read property 'email' of undefined` editor is totally busted.

I don't get it on new forms, or on create form template. What is unique about this form?

**Comment by Desertsnowman** [comment]
Crudmonkeys ! I'll get on it when I get back to my pc.

**Comment by Desertsnowman** [comment]
@Shelob9 - field binding `{{_field type="email"}}` etc was trying to initialise before fields exist
