### ISSUE TITLE
Two forms, one in modal, on same page adds message to wrong form

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#556]
Check this out: http://calderawp.staging.wpengine.com/ignore-me/
Submit the modal form, the success message goes on the other form. Totally puntable to 1.3.6 if it is not a quick fix.

**Comment by Desertsnowman** [comment]
this is actually a know issue. if you have two forms on a page and submit one without ajax, both forms get the notice... I think will check and confirm. either way needs to be fixed

**Comment by Desertsnowman** [comment]
Oh also the ajax pushing notices is known, it pushes to the first instance of the form if its the same

**Comment by Desertsnowman** [comment]
I'm going to move this to 1.3.5 since I think I can fix quickly. else I'll punt it to .6

**Comment by Desertsnowman** [comment]
closed via f7b8c98
