### ISSUE TITLE
email Field

### ISSUE THREAD

**Issue by webline** [Desertsnowman/Caldera-Forms#69]
If an input field comes with type=email the CSS styles you use for the type=text inputs is missing. The look of the field seems to be broken.
The CSS rules for input[type="email"] are missing.

**Comment by Desertsnowman** [comment]
Hi there,
Do you have an example online somewhere I can see this?

**Comment by webline** [comment]
After adding:
input[type="email"] {
    box-shadow: 0 1px 5px rgba(0, 0, 0, 0.1) inset;
    border: 1px solid #d2d2d2;
    box-shadow: 0 1px 5px rgba(0, 0, 0, 0.1) inset;
    box-sizing: border-box;
    color: #747474;
    font-size: 13px;
    margin-right: 1%;
    padding: 8px 15px;
    width: 100%;
}
to my themes custom CSS the email field looks like the text inputs.
Just playing around with your plugin - so no demo so far.

Detlef

**Comment by Desertsnowman** [comment]
if you look in caldera forms admin, in the top header there are 3 buttons:
![screen shot 2015-02-12 at 10 27 36 am](https://cloud.githubusercontent.com/assets/307466/6163988/f74c1670-b2a1-11e4-923a-30e32e6170b9.png)
Is the Form button highlighted?

**Comment by webline** [comment]
that helped - I removed my custom CSS and after selecting all buttons the problem was gone!
Perfekt - thanks a lot.

Detlef

**Comment by Desertsnowman** [comment]
does this solve #70 as well?
