### ISSUE TITLE
textarea cols option

### ISSUE THREAD

**Issue by webline** [Desertsnowman/Caldera-Forms#70]
Hi David,

don't know if this is a problem related with the theme I use or with your plugin.
All text input fields use the available width of the content area where I place the form (width: 100%;). The email input and the textarea inputs don't use width: 100% and so they look too small related to the rest of the form.
A CSS rule or a cols option for the text area would help here.

Thanks,

Detlef

**Comment by Desertsnowman** [comment]
relates to #69

**Comment by webline** [comment]
solved with your tip in #69 

thanks!
