### ISSUE TITLE
Custom Class is not being outputed

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#73]
Reported here:

https://wordpress.org/support/topic/adding-custom-class-to-content-html-box-?replies=3

**Comment by metanoia77** [comment]
Any News on this ? I found out you can't even use classes inside the HTML box either. Inline CSS is messy and breaks responsiveness.

**Comment by Desertsnowman** [comment]
almost. huge update coming in the next few weeks.

**Comment by metanoia77** [comment]
Thanks - sounds GOOD !!!!!!!! :-)

**Comment by metanoia77** [comment]
Excellent News  - this is an epic plugin :-)
