### ISSUE TITLE
{ip} magic tag not working in mailer body?

### ISSUE THREAD

**Issue by sglfree** [Desertsnowman/Caldera-Forms#74]
I'd like to track IP addresses of submits but it seems no way to see it in form's entry data. When I tried to place a {ip} magic tag in form's mailer message body the auto mailer failed to send the mail. If just leave the default {summary} it works fine. Is there any misconfiguration in my settings or it's a code bug? It may have other ways to track the IP address in entry record? 

Thank you very much for any help!

**Comment by sglfree** [comment]
I just looked into the code and found the repo on Wordpress.org had not been synchronized with github(the same 1.1.9.3 version) so the {ip} magic tag failed to work. BTW, I made a pull request to fix a little bug found in function do_magic_tags and add a new {ua} tag to facilitate record of user agent string of form commits. Hope this will help,thank you for this free plugin!

**Comment by Desertsnowman** [comment]
fixed in latest version

**Comment by shahidali788** [comment]
I am not getting complete IP address in Entries. Have look screenshto. Can you please tell me how can I fix it. 
http://prntscr.com/7z6m9c
I have done everything correctly. I am getting this error. Not getting complete IP Address.
