### ISSUE TITLE
ReCaptcha not working 

### ISSUE THREAD

**Issue by Sap-Design-Team** [Desertsnowman/Caldera-Forms#86]
ReCaptcha works as a widget but does not work in the form itself.
Running WordPress Version 4.1.1 

Maybe the cause for this is because I have a drop down slider at the top of my page which is closed by default with a form widget placed inside and a Caldera-Form in the page below.

Any one have any issues with two ReCaptcha on a page?

Any information to resolve this would greatly be appreciated,
Thank You All

**Comment by Sap-Design-Team** [comment]
I was correct two ReCaptcha do not work on the same page. This isn't Google's ReCaptcha API because two ReCaptcha do work, but not with the same plugin. I have a contact page with a ReCaptcha set within my theme and a drop down slider at the top of the page with a  Caldera-Form containing a ReCaptcha as a widget which works displaying both in the drop down slider and in the contact form on the page. I also ran across another issue using conditions to hide the ReCaptcha in the Caldera-Form which on show the text / Name of the field shows but the ReCaptcha does not. All of this worked fine before the latest update.

**Comment by Desertsnowman** [comment]
Related to a new issue #97 which is being sorted today
