### ISSUE TITLE
Upgraded to Version 1.1.9.4 and my forms stoped working

### ISSUE THREAD

**Issue by Keste68** [Desertsnowman/Caldera-Forms#88]
Upgraded to Version 1.1.9.4 and my forms stoped working. Even if I have not enabled required fields the next or previus page button doesnt work any more for my forms.... :(

**Comment by Desertsnowman** [comment]
I'll take a look and see what I can find out. Does down grading solve the problem?

-------- Original message --------

**Comment by Keste68** [comment]
Yes, downgrading solved the problem. :)

**Comment by Desertsnowman** [comment]
is the site online somewhere i can see it?

**Comment by Keste68** [comment]
Hi David,

http://lessismoreit.se/limit-klientatertag/

I could not proceed from step 3 by clicking on Next when I upgraded….

Mvh
Kenneth Steinholtz

[cid:image003.png@01D06708.C7FE8590]

Mobil: 076-7233252
Epost: kenneth.steinholtz@lessismoreit.se<mailto:kenneth.steinholtz@lessismoreit.se>

LESS IS MORE IT AB
Grindstuvägen 48, 3 tr
167 33 Bromma
Telefon: 08 – 704 15 04
Webb: www.lessismoreit.se<http://www.lessismoreit.se>


Från: David Cramer [mailto:notifications@github.com]
Skickat: den 25 mars 2015 09:18
Till: Desertsnowman/Caldera-Forms
Kopia: Kenneth Steinholtz
Ämne: Re: [Caldera-Forms] Upgraded to Version 1.1.9.4 and my forms stoped working (#88)


is the site online somewhere i can see it?

**Comment by Desertsnowman** [comment]
Can you upgrade it again so I can check it in the broken state?

**Comment by Keste68** [comment]
Upgraded!


Mvh
Kenneth Steinholtz

[cid:image001.png@01D0670A.213B1B40]

Mobil: 076-7233252
Epost: kenneth.steinholtz@lessismoreit.se<mailto:kenneth.steinholtz@lessismoreit.se>

LESS IS MORE IT AB
Grindstuvägen 48, 3 tr
167 33 Bromma
Telefon: 08 – 704 15 04
Webb: www.lessismoreit.se<http://www.lessismoreit.se>


Från: David Cramer [mailto:notifications@github.com]
Skickat: den 25 mars 2015 14:39
Till: Desertsnowman/Caldera-Forms
Kopia: Kenneth Steinholtz
Ämne: Re: [Caldera-Forms] Upgraded to Version 1.1.9.4 and my forms stoped working (#88)


Can you upgrade it again so I can check it in the broken state?

**Comment by Desertsnowman** [comment]
ok. you can downgrade again. would you be able to send me an export of the form?

**Comment by Keste68** [comment]
Hi David,

Here is the form exported with the new version installed.

☺


Mvh
Kenneth Steinholtz

[cid:image001.png@01D0670D.07F6B970]

Mobil: 076-7233252
Epost: kenneth.steinholtz@lessismoreit.se<mailto:kenneth.steinholtz@lessismoreit.se>

LESS IS MORE IT AB
Grindstuvägen 48, 3 tr
167 33 Bromma
Telefon: 08 – 704 15 04
Webb: www.lessismoreit.se<http://www.lessismoreit.se>


Från: David Cramer [mailto:notifications@github.com]
Skickat: den 25 mars 2015 15:00
Till: Desertsnowman/Caldera-Forms
Kopia: Kenneth Steinholtz
Ämne: Re: [Caldera-Forms] Upgraded to Version 1.1.9.4 and my forms stoped working (#88)


ok. you can downgrade again. would you be able to send me an export of the form?

**Comment by Desertsnowman** [comment]
umm can you mail it to david@caldera.co.za ?

**Comment by Desertsnowman** [comment]
perfect. I can replicate the problem. I'll sort it out and let you know

**Comment by Keste68** [comment]
Great!


Mvh
Kenneth Steinholtz

[cid:image002.png@01D06712.0AE77E80]

Mobil: 076-7233252
Epost: kenneth.steinholtz@lessismoreit.se<mailto:kenneth.steinholtz@lessismoreit.se>

LESS IS MORE IT AB
Grindstuvägen 48, 3 tr
167 33 Bromma
Telefon: 08 – 704 15 04
Webb: www.lessismoreit.se<http://www.lessismoreit.se>


Från: David Cramer [mailto:notifications@github.com]
Skickat: den 25 mars 2015 15:34
Till: Desertsnowman/Caldera-Forms
Kopia: Kenneth Steinholtz
Ämne: Re: [Caldera-Forms] Upgraded to Version 1.1.9.4 and my forms stoped working (#88)


perfect. I can replicate the problem. I'll sort it out and let you know

**Comment by Keste68** [comment]
Thanks!!!
