### ISSUE TITLE
Quotes are not decoding properly in emails

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#92]
Emails with single or double quotes are sent with `\'` and `\"`s in them.

**Comment by pippinsplugins** [comment]
It looks like slashes are stripped a few times but one of the sanitization functions seems to be adding them back in. The changes in #95 ensures slashes are stripped as late as possible.

**Comment by Desertsnowman** [comment]
Thanks @pippinsplugins for this. Much appreciated.
