### ISSUE TITLE
Format calculation output field?

### ISSUE THREAD

**Issue by Keste68** [Desertsnowman/Caldera-Forms#94]
Hi, Is there some way to format the calculation output field?

I'm doing a form with money calculation and i would like to have the output figures seperated with a "blank" space or a "." like this:

1 280 900 €
1.280.900 €
1 280 900.00 €
1.280.900.00 €

Is it possible?

/Kenneth

**Comment by Desertsnowman** [comment]
I made the money format option extend down to this. not with a . or space, but with a comma. like:
10,00.00
1,000,00.00 etc.

Is this acceptable?

**Comment by Keste68** [comment]
Thats great!

Thanks!!!


Mvh
Kenneth Steinholtz

[cid:image002.png@01D072D4.30FC51E0]

Mobil: 076-7233252
Epost: kenneth.steinholtz@lessismoreit.se<mailto:kenneth.steinholtz@lessismoreit.se>

LESS IS MORE IT AB
Grindstuvägen 48, 3 tr
167 33 Bromma
Telefon: 08 – 704 15 04
Webb: www.lessismoreit.se<http://www.lessismoreit.se>


Från: David Cramer [mailto:notifications@github.com]
Skickat: den 9 april 2015 12:49
Till: Desertsnowman/Caldera-Forms
Kopia: Kenneth Steinholtz
Ämne: Re: [Caldera-Forms] Format calculation output field? (#94)


I made the money format option extend down to this. not with a . or space, but with a comma. like:
10,00.00
1,000,00.00 etc.

Is this acceptable?
